'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import {
  ArrowRight, BellRing, Bot, Building2, Check, CheckCircle2, ChevronDown, CircleDollarSign,
  Clock3, Cookie, FileCheck2, FileSearch, Globe2, LayoutDashboard, Menu, MessageSquareText,
  MoveUpRight, Search, Send, ShieldCheck, Sparkles, Target, UsersRound, X, Zap,
} from 'lucide-react';
import { company, faq, legalPages, nav, productPages, solutionPages } from './config';

const ui = {
  fr: { demo: 'Demander une démo', login: 'Se connecter', menu: 'Menu', close: 'Fermer', eyebrow: 'IA pour les marchés publics au Maroc', hero: 'L’analyseur IA des marchés publics conçu pour les entreprises marocaines.', sub: 'Bido centralise les appels d’offres et bons de commande, recherche dans les dossiers, qualifie leur pertinence et aide votre équipe à décider plus vite — toujours sous contrôle humain.', primary: 'Découvrir l’analyseur IA', secondary: 'Voir comment ça marche', trusted: 'Conçu pour les équipes qui répondent aux marchés publics avec méthode', language: 'Langue' },
  en: { demo: 'Book a demo', login: 'Sign in', menu: 'Menu', close: 'Close', eyebrow: 'Public procurement intelligence', hero: 'Decide faster on the opportunities that matter.', sub: 'Bido detects, qualifies and structures public procurement opportunities to turn monitoring into actionable decisions.', primary: 'Discover Bido', secondary: 'See how it works', trusted: 'Built for teams who bid methodically', language: 'Language' },
  ar: { demo: 'طلب عرض توضيحي', login: 'تسجيل الدخول', menu: 'القائمة', close: 'إغلاق', eyebrow: 'ذكاء الصفقات العمومية', hero: 'اتخذ قرارك بسرعة بشأن الفرص التي تستحق.', sub: 'تكتشف Bido فرص الصفقات العمومية وتؤهلها وتنظمها، لتحويل عملية الرصد إلى قرارات عملية.', primary: 'اكتشف Bido', secondary: 'كيف تعمل المنصة', trusted: 'مصممة للفرق التي تستجيب بمنهجية', language: 'اللغة' },
};

function Logo({ light = false }) {
  return <Link href="/" className={`logo ${light ? 'logo-light' : ''}`} aria-label="Bido, accueil"><span className="logo-mark"><i /><i /><i /></span><span>Bido<em>.ma</em></span></Link>;
}

function Header({ locale, setLocale }) {
  const [open, setOpen] = useState(false);
  const [active, setActive] = useState(null);
  const t = ui[locale];
  const pathname = usePathname();
  useEffect(() => { setOpen(false); setActive(null); }, [pathname]);
  return <>
    <header className="site-header">
      <div className="nav-wrap">
        <Logo />
        <nav className="desktop-nav" aria-label="Navigation principale">
          {nav.map(([label, value]) => Array.isArray(value) ? <div className="nav-dropdown" key={label} onMouseEnter={() => setActive(label)} onMouseLeave={() => setActive(null)}>
            <button aria-expanded={active === label} onClick={() => setActive(active === label ? null : label)}>{label}<ChevronDown size={14} /></button>
            {active === label && <div className="dropdown-panel">{value.map(([text, path]) => <Link key={path} href={path}><span>{text}</span><ArrowRight size={14} /></Link>)}</div>}
          </div> : <Link className={pathname === value ? 'active' : undefined} key={value} href={value}>{label}</Link>)}
        </nav>
        <div className="header-actions">
          <label className="locale-select"><Globe2 size={16}/><span className="sr-only">{t.language}</span><select value={locale} onChange={e => setLocale(e.target.value)}><option value="fr">FR</option><option value="ar">AR</option><option value="en">EN</option></select></label>
          <a href={company.loginUrl} className="text-link">{t.login}</a>
          <Link href="/demo" className="button small">{t.demo}<ArrowRight size={15}/></Link>
          <button className="menu-button" onClick={() => setOpen(true)} aria-label={t.menu}><Menu/></button>
        </div>
      </div>
    </header>
    {open && <div className="mobile-panel" role="dialog" aria-modal="true" aria-label="Navigation mobile">
      <div className="mobile-top"><Logo/><button onClick={() => setOpen(false)} aria-label={t.close}><X/></button></div>
      <nav>{nav.map(([label, value]) => <div key={label}><strong>{label}</strong>{Array.isArray(value) ? value.slice(0,5).map(([text,path]) => <Link key={path} href={path}>{text}</Link>) : <Link href={value}>{label}</Link>}</div>)}</nav>
      <Link href="/demo" className="button">{t.demo}<ArrowRight size={16}/></Link>
    </div>}
  </>;
}

function Notice() { return <div className="notice"><span>Nouveau</span><p>La liste d’attente Bido est ouverte aux entreprises marocaines.</p><Link href="/demo">Rejoindre l’accès anticipé <ArrowRight size={14}/></Link></div>; }

function ProductMockup() {
  const opportunities = [
    ['Travaux d’aménagement urbain', 'Agadir', '92', '12 j'],
    ['Étude technique & suivi', 'Tiznit', '87', '18 j'],
    ['Équipements informatiques', 'Rabat', '76', '8 j'],
  ];
  return <div className="mock-shell" aria-label="Aperçu de l’interface Bido">
    <div className="mock-top"><div className="mock-brand"><span/><b>Bido</b></div><div className="mock-search"><Search size={13}/>Rechercher une opportunité…</div><div className="avatar">HB</div></div>
    <div className="mock-body">
      <aside><LayoutDashboard size={16}/><Search size={16}/><FileCheck2 size={16}/><Bot size={16}/><UsersRound size={16}/></aside>
      <main>
        <div className="mock-heading"><div><small>VOTRE PIPELINE</small><h3>Opportunités recommandées</h3></div><button>+ Nouvelle veille</button></div>
        <div className="mini-stats"><div><span>À qualifier</span><strong>24</strong><small>+6 cette semaine</small></div><div><span>En analyse</span><strong>08</strong><small>3 urgentes</small></div><div><span>À soumettre</span><strong>05</strong><small>Ce mois</small></div></div>
        <div className="opportunity-table"><div className="table-head"><span>Opportunité</span><span>Score</span><span>Échéance</span></div>{opportunities.map(([name,city,score,date],i)=><div className="table-row" key={name}><div><i className={`file-icon c${i}`}><FileSearch size={15}/></i><span><b>{name}</b><small>{city} · Travaux / services</small></span></div><span className="score">{score}%</span><span>{date}</span></div>)}</div>
      </main>
    </div>
    <div className="analysis-float"><div><Sparkles size={14}/><b>Analyse Bido</b><span>Prête</span></div><p>Adéquation forte avec votre profil BTP Souss-Massa.</p><div className="progress"><i/></div></div>
  </div>;
}

function Home({ locale }) {
  const t = ui[locale];
  return <main id="main">
    <section className="hero"><div className="blueprint"/><div className="container"><Notice/><div className="hero-grid">
      <div className="hero-copy"><div className="eyebrow"><span/><b>{t.eyebrow}</b></div><h1>{t.hero}</h1><p>{t.sub}</p><div className="hero-actions"><Link className="button" href="/plateforme">{t.primary}<ArrowRight size={17}/></Link><a className="button ghost" href="#workflow">{t.secondary}</a></div><div className="hero-proof"><div className="faces"><span>AM</span><span>SA</span><span>YK</span></div><p><b>Une plateforme pensée au Maroc,</b><br/>pour les réalités des entreprises marocaines.</p></div></div>
      <ProductMockup/>
    </div></div></section>

    <section className="trust-strip"><div className="container"><span>{t.trusted}</span><div><b><Building2/>BTP & INGÉNIERIE</b><b><Zap/>ÉNERGIE</b><b><Target/>CONSEIL</b><b><CircleDollarSign/>SERVICES</b><b><Globe2/>TECHNOLOGIE</b></div></div></section>

    <section className="section problem"><div className="container narrow"><div className="section-label">LE CONSTAT</div><h2>La bonne opportunité existe.<br/>Le défi, c’est de la voir à temps.</h2><p className="lead">Vos équipes ne devraient pas passer leurs journées à chercher, ouvrir et trier des dossiers. Elles devraient décider où concentrer leur expertise.</p><div className="problem-grid">{[[Clock3,'Des heures de veille','La recherche manuelle disperse l’attention sur des avis peu pertinents.'],[FileSearch,'Des dossiers denses','Les exigences critiques sont noyées dans des dizaines de pièces.'],[MessageSquareText,'Des décisions fragmentées','Notes, validations et responsabilités circulent entre plusieurs canaux.']].map(([Icon,title,text],i)=><article key={title}><span>0{i+1}</span><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

    <section className="section platform-section"><div className="container"><div className="split-heading"><div><div className="section-label light">LA PLATEFORME</div><h2>Un seul environnement.<br/>De la veille à la décision.</h2></div><p>Bido structure chaque étape de votre processus pour créer un pipeline clair, comparable et pilotable.</p></div><div className="platform-grid">{[
      [Search,'Détecter','Centralisez les opportunités et filtrez-les selon vos activités, zones et priorités.'],
      [Target,'Qualifier','Mesurez l’adéquation de chaque dossier avec votre profil et vos capacités.'],
      [Sparkles,'Comprendre','Synthétisez les pièces et rendez visibles les exigences qui comptent.'],
      [UsersRound,'Coordonner','Attribuez, commentez et documentez chaque décision en équipe.'],
    ].map(([Icon,title,text],i)=><article key={title}><div className="num">0{i+1}</div><Icon/><h3>{title}</h3><p>{text}</p><Link href="/plateforme">Explorer <MoveUpRight size={15}/></Link></article>)}</div></div></section>

    <section className="section workflow" id="workflow"><div className="container"><div className="feature-layout"><div className="feature-copy"><div className="section-label">DÉCOUVERTE DES OPPORTUNITÉS</div><h2>Votre veille marchés publics devient un avantage opérationnel.</h2><p>Créez des profils de recherche alignés sur vos métiers. Bido fait remonter les appels d’offres et bons de commande utiles, sans ensevelir votre équipe sous les notifications.</p><ul><li><CheckCircle2/>Filtres sectoriels, géographiques et sémantiques</li><li><CheckCircle2/>Recherches sauvegardées et listes de veille</li><li><CheckCircle2/>Pertinence expliquée selon votre profil d’entreprise</li></ul><Link href="/opportunites" className="inline-cta">Découvrir la veille Bido <ArrowRight/></Link></div><OpportunityPanel/></div></div></section>

    <section className="section ai-section"><div className="container"><div className="ai-grid"><AnalysisPanel/><div className="feature-copy"><div className="section-label light">ANALYSE IA DES MARCHÉS PUBLICS</div><h2>Du dossier volumineux<br/>à une lecture structurée.</h2><p>Bido recherche dans les pièces disponibles, fait ressortir les exigences utiles et prépare une analyse contextualisée sans masquer les sources à vérifier.</p><div className="quote-line"><ShieldCheck/><p><b>L’IA assiste. Votre équipe décide.</b><br/>Chaque synthèse importante reste soumise à validation humaine.</p></div><Link href="/analyseur-ia-marches-publics" className="inline-cta light-link">Découvrir l’analyseur IA <ArrowRight/></Link></div></div></div></section>

    <section className="section outcomes"><div className="container"><div className="center-heading"><div className="section-label">IMPACT OPÉRATIONNEL</div><h2>Moins de friction.<br/>Plus de décisions utiles.</h2></div><div className="outcome-grid">{[['01','Voir plus tôt','Repérez les opportunités pertinentes avant que le délai devienne une contrainte.'],['02','Lire plus vite','Accédez à une synthèse structurée tout en gardant le lien avec les pièces sources.'],['03','Décider ensemble','Formalisez vos critères et conservez une trace claire des arbitrages.'],['04','Répondre avec méthode','Organisez actions, exigences et responsabilités dans un même flux.']].map(([n,title,text])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

    <HomeSeoOverview/><PricingPreview/><FAQBlock preview/><FinalCTA/>
  </main>;
}

function OpportunityPanel(){return <div className="opportunity-panel"><div className="panel-toolbar"><span><Search size={15}/>Voirie, VRD, études techniques</span><button>Filtres <b>4</b></button></div><div className="op-card selected"><div className="op-card-top"><span className="op-type">TRAVAUX</span><span className="match">Pertinence 92%</span></div><h4>Travaux d’aménagement et de mise à niveau urbaine</h4><p>Commune territoriale · Région Souss-Massa</p><div className="op-facts"><span><b>Budget estimé</b>2,4 M MAD</span><span><b>Échéance</b>26 juillet 2026</span></div><div className="tags"><i>VRD</i><i>Voirie</i><i>Province ciblée</i></div></div><div className="op-card"><div className="op-card-top"><span className="op-type service">SERVICES</span><span className="match medium">Pertinence 84%</span></div><h4>Études techniques et suivi des travaux d’équipement</h4><p>Établissement public · Agadir</p></div><div className="alert-chip"><BellRing/><span><b>Veille active</b>3 nouvelles opportunités pertinentes</span></div></div>}

function AnalysisPanel(){return <div className="analysis-panel"><div className="doc-side"><div className="doc-header"><FileCheck2/><span><b>CPS — Étude technique.pdf</b><small>64 pages · analysé</small></span></div><div className="doc-lines"><b/><i/><i/><i/><b/><i/><i/><i/><i/><b/><i/></div></div><div className="ai-side"><div className="ai-head"><span><Sparkles/>Synthèse exécutive</span><b>IA</b></div><div className="risk-box"><i>POINT D’ATTENTION</i><p>La visite des lieux est obligatoire avant le dépôt.</p><small>Source : RC, page 12</small></div>{[['Objet','Étude et suivi de 4 ouvrages'],['Délai d’exécution','8 mois'],['Qualification','D4 · Classe 3'],['Caution provisoire','28 000 MAD']].map(([a,b])=><div className="analysis-row" key={a}><span>{a}</span><b>{b}</b></div>)}<button>Poser une question au dossier <ArrowRight/></button></div></div>}

function PricingPreview(){return <section className="section pricing-preview"><div className="container"><div className="split-heading"><div><div className="section-label">UNE OFFRE LISIBLE</div><h2>Commencez à votre rythme.<br/>Structurez à mesure.</h2></div><p>Les tarifs définitifs seront publiés avant le lancement. Inscrivez-vous pour participer au programme d’accès anticipé.</p></div><div className="plan-grid">{[['Starter','Pour démarrer une veille ciblée',['1 utilisateur','Veilles enregistrées','Synthèses essentielles']],['Professional','Pour piloter un pipeline actif',['5 utilisateurs','Analyse documentaire','Collaboration & reporting']],['Entreprise','Pour les organisations multi-équipes',['Utilisateurs adaptés','Contrôles avancés','Intégrations sur étude']]].map(([name,text,items],i)=><article className={i===1?'featured':''} key={name}>{i===1&&<span className="popular">RECOMMANDÉ</span>}<h3>{name}</h3><p>{text}</p><div className="price">Sur demande</div><ul>{items.map(x=><li key={x}><Check/>{x}</li>)}</ul><Link href="/demo" className={`button ${i===1?'':'outline'}`}>Rejoindre la liste<ArrowRight/></Link></article>)}</div><div className="pricing-link"><Link href="/tarifs">Comparer les offres en détail <ArrowRight/></Link></div></div></section>}

function FAQBlock({preview=false}){const items=preview?faq.slice(0,4):faq;return <section className="section faq-section"><div className="container faq-layout"><div><div className="section-label">QUESTIONS FRÉQUENTES</div><h2>Des réponses nettes,<br/>avant de commencer.</h2><p>Une question spécifique à votre organisation ?</p><Link href="/contact">Parler à notre équipe <ArrowRight/></Link></div><div className="accordion">{items.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>}

function FinalCTA(){return <section className="final-cta"><div className="cta-grid"/><div className="container"><span>PRÊT À STRUCTURER VOTRE VEILLE ?</span><h2>Les marchés publics demandent<br/>de la méthode. Bido aussi.</h2><p>Rejoignez les entreprises qui souhaitent tester la prochaine génération d’outils de veille et d’analyse.</p><div><Link className="button white" href="/demo">Demander un accès anticipé <ArrowRight/></Link><Link className="button dark-ghost" href="/contact">Parler à l’équipe</Link></div></div></section>}

function HomeSeoOverview(){const cards=[['Appels d’offres et bons de commande','Consultez un flux structuré d’opportunités publiques au Maroc.','/opportunites'],['Recherche intelligente','Formulez votre besoin en langage naturel et affinez les critères interprétés.','/recherche-intelligente-marches-publics'],['Recherche avancée','Combinez acheteur, région, budget, procédure, lots, dates et documents.','/recherche-avancee-appels-offres'],['Recherche dans les documents','Retrouvez une exigence dans les pièces disponibles, pas seulement dans le titre.','/recherche-documents-appels-offres'],['Pertinence pour votre entreprise','Classez les opportunités selon votre profil métier sans confondre score et éligibilité.','/pertinence-opportunites-marches-publics'],['Analyse IA du dossier','Posez vos questions, préparez une synthèse et vérifiez les références officielles.','/analyseur-ia-marches-publics']];return <section className="section seo-overview"><div className="container"><div className="split-heading"><div><div className="section-label">LOGICIEL DE MARCHÉS PUBLICS</div><h2>Un workflow complet pour rechercher, qualifier et analyser.</h2></div><div><p>Bido aide les entreprises marocaines à transformer la veille marchés publics en un processus continu : découvrir les appels d’offres, comprendre les dossiers, mesurer la pertinence et coordonner la décision.</p><p>La plateforme reste indépendante des autorités publiques. Les documents officiels demeurent la référence pour les conditions, délais et modalités de soumission.</p></div></div><div className="seo-card-grid">{cards.map(([title,text,href])=><article key={href}><h3>{title}</h3><p>{text}</p><Link href={href}>Découvrir cette fonctionnalité <ArrowRight/></Link></article>)}</div></div></section>}

function StandardPage({data}){const Icon=data.icon;return <main id="main"><section className="page-hero"><div className="blueprint"/><div className="container"><div className="page-hero-grid"><div><div className="eyebrow"><span/><b>{data.eyebrow}</b></div><h1>{data.title}</h1><p>{data.text}</p><div className="hero-actions"><Link className="button" href="/demo">Demander une démo <ArrowRight/></Link><Link className="button ghost" href="/tarifs">Voir les tarifs</Link></div></div><div className="page-icon-card"><Icon/><div className="rings"/><span>BIDO / {data.eyebrow.toUpperCase()}</span></div></div><div className="metric-row">{data.metrics.map(([a,b])=><div key={a}><strong>{a}</strong><span>{b}</span></div>)}</div></div></section><section className="section"><div className="container"><div className="center-heading"><div className="section-label">CAPACITÉS</div><h2>Une fonctionnalité conçue pour<br/>un usage opérationnel réel.</h2></div><div className="detail-cards">{data.features.map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p><ArrowRight/></article>)}</div></div></section>{data.sections?.length>0&&<section className="section editorial-sections"><div className="container">{data.sections.map(([title,text,items],index)=><article className="editorial-block" key={title}><div className="editorial-heading"><span>{String(index+1).padStart(2,'0')}</span><div><h2>{title}</h2><p>{text}</p></div></div><div className="editorial-points">{items.map(([itemTitle,itemText])=><div key={itemTitle}><CheckCircle2/><h3>{itemTitle}</h3><p>{itemText}</p></div>)}</div></article>)}</div></section>}{data.faqs?.length>0&&<section className="section page-faq"><div className="container faq-layout"><div><div className="section-label">QUESTIONS SUR CETTE FONCTIONNALITÉ</div><h2>Ce qu’il faut savoir avant de commencer.</h2></div><div className="accordion">{data.faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>}<WorkflowBand/><FinalCTA/></main>}

function WorkflowBand(){return <section className="workflow-band"><div className="container"><p>UN FLUX DE TRAVAIL COMPLET</p><div>{[['01','Détecter'],['02','Qualifier'],['03','Analyser'],['04','Décider']].map(([n,t],i)=><span key={t}><b>{n}</b>{t}{i<3&&<ArrowRight/>}</span>)}</div></div></section>}

function SolutionPage({data}){const [eyebrow,title,text,Icon]=data;return <StandardPage data={{eyebrow:`Solution · ${eyebrow}`,title,text,icon:Icon,metrics:[['Focus','sur votre métier'],['Méthode','partagée'],['Décision','documentée']],features:[['Une veille adaptée',`Configurez Bido autour des priorités propres aux équipes ${eyebrow.toLowerCase()}.`],['Des analyses homogènes','Appliquez la même grille de lecture à chaque opportunité sans perdre votre jugement.'],['Un pilotage clair','Partagez l’avancement, les échéances et les arbitrages avec les décideurs.']],sections:[['Détectez les opportunités adaptées à votre contexte',`Votre veille marchés publics doit refléter les activités, territoires, capacités et priorités propres à ${eyebrow.toLowerCase()}.`,[['Profil métier','Décrivez les prestations, secteurs et zones réellement couverts.'],['Recherche ciblée','Combinez mots-clés, filtres et recherche dans les documents.'],['Listes de veille','Organisez les opportunités par objectif ou responsable.']]],['Qualifiez avant de mobiliser les ressources','Une première lecture structurée permet de concentrer les experts sur les dossiers qui méritent une analyse approfondie.',[['Pertinence expliquée','Identifiez les signaux rapprochant le dossier de votre profil.'],['Exigences à vérifier','Repérez les critères, pièces, dates et risques importants.'],['Décision Go / No-Go','Documentez les raisons et réserves avant de poursuivre.']]],['Coordonnez la réponse dans un espace commun','Bido rassemble les informations, documents, notes, responsabilités et échéances autour de chaque opportunité.',[['Attribution','Clarifiez qui analyse, contrôle et valide.'],['Historique','Conservez les décisions et changements de statut.'],['Reporting','Partagez une synthèse lisible avec les décideurs.']]] ]}}/>}

function Pricing(){const plans=[['Starter','Veille essentielle',['1 utilisateur','3 profils de veille','Alertes email','Listes enregistrées','Synthèses essentielles']],['Professional','Pipeline complet',['5 utilisateurs','Veilles illimitées','Analyse documentaire','Collaboration','Reporting & exports']],['Business','Équipes avancées',['15 utilisateurs','Espaces équipe','Rôles avancés','Agents configurables','Support prioritaire']],['Entreprise','Sur mesure',['Multi-entités','SAML / SSO sur étude','Intégrations dédiées','Accompagnement','Cadre contractuel adapté']]];return <main id="main"><PageIntro eyebrow="Tarifs" title="Une structure simple. Des capacités qui évoluent avec vous." text="Les prix ci-dessous restent volontairement sur demande pendant la phase d’accès anticipé. Aucun faux prix, aucun engagement caché."/><section className="section pricing-page"><div className="container"><div className="plan-grid four">{plans.map(([name,desc,items],i)=><article className={i===1?'featured':''} key={name}>{i===1&&<span className="popular">LE PLUS CHOISI</span>}<h3>{name}</h3><p>{desc}</p><div className="price">Sur demande</div><small>Tarification adaptée au périmètre</small><ul>{items.map(x=><li key={x}><Check/>{x}</li>)}</ul><Link href="/demo" className={`button ${i===1?'':'outline'}`}>Nous contacter<ArrowRight/></Link></article>)}</div><div className="pricing-note"><ShieldCheck/><p><b>Transparence avant engagement.</b> Le périmètre fonctionnel, les limites d’usage, le support et les conditions de traitement des données seront détaillés dans chaque offre.</p></div></div></section><FAQBlock/><FinalCTA/></main>}

function PageIntro({eyebrow,title,text}){return <section className="simple-hero"><div className="blueprint"/><div className="container"><div className="eyebrow"><span/><b>{eyebrow}</b></div><h1>{title}</h1><p>{text}</p></div></section>}

function ContactForm({demo=false}){const [sent,setSent]=useState(false);function submit(e){e.preventDefault();setSent(true)}if(sent)return <div className="form-success"><CheckCircle2/><h3>Votre demande est prête à être transmise</h3><p>Cette version de démonstration n’envoie encore aucune donnée. Le message de confirmation définitif sera activé avec le formulaire sécurisé.</p><button onClick={()=>setSent(false)} className="button outline">Revenir au formulaire</button></div>;return <form className="contact-form" onSubmit={submit}>{!demo&&<label>Objet de la demande<select required name="subject" defaultValue=""><option value="" disabled>Sélectionnez un sujet</option><option>Demande commerciale</option><option>Support produit</option><option>Partenariat</option><option>Question générale</option><option>Confidentialité et données</option><option>Signaler un problème de données</option><option>Presse</option><option>Autre</option></select></label>}<div className="form-row"><label>Prénom et nom<input required name="name" placeholder="Votre prénom et votre nom"/></label><label>Adresse e-mail professionnelle<input required type="email" name="email" placeholder="nom@entreprise.ma"/></label></div><div className="form-row"><label>Entreprise<input required name="company" placeholder="Nom de votre entreprise"/></label><label>Fonction<input name="role" placeholder="Ex. Responsable appels d’offres"/></label></div>{demo&&<div className="form-row"><label>Taille de l’équipe<select name="team"><option>1 à 5 personnes</option><option>6 à 20 personnes</option><option>Plus de 20 personnes</option></select></label><label>Secteur principal<select name="sector"><option>BTP et ingénierie</option><option>Services aux entreprises</option><option>Informatique et numérique</option><option>Fournitures et équipements</option><option>Conseil et formation</option><option>Autre</option></select></label></div>}<label>{demo?'Votre processus actuel':'Votre message'}<textarea required name="message" rows="5" placeholder={demo?'Comment recherchez-vous et qualifiez-vous actuellement les marchés publics ?':'Décrivez votre demande avec la référence utile, sans transmettre de document sensible.'}/></label><label className="checkbox"><input required type="checkbox"/><span>J’accepte que Bido utilise ces informations uniquement pour traiter ma demande, conformément à la politique de confidentialité.</span></label><button className="button" type="submit">{demo?'Demander une démonstration':'Envoyer ma demande'} <Send size={16}/></button><small>Ne transmettez aucun mot de passe, document confidentiel ou donnée personnelle non nécessaire.</small></form>}

function Contact({demo=false}){const points=demo?[[MessageSquareText,'Démonstration contextualisée','Nous partons de vos secteurs, critères de veille et méthodes de qualification.'],[Clock3,'Parcours de 30 à 45 minutes','Découverte, recherche, analyse IA, collaboration et questions.'],[ShieldCheck,'Aucun dossier sensible requis','Des exemples de démonstration suffisent pour présenter le workflow.']]:[[MessageSquareText,'Demande orientée','Choisissez commercial, support, partenariat, données, presse ou autre.'],[Clock3,'Contexte utile','Une référence et une description claire facilitent le traitement.'],[ShieldCheck,'Confidentialité','Ne partagez aucun document sensible dans ce formulaire.']];return <main id="main"><section className="contact-section"><div className="container contact-grid"><div><div className="eyebrow"><span/><b>{demo?'Démonstration Bido':'Contacter Bido.ma'}</b></div><h1>{demo?'Découvrez comment analyser vos marchés publics avec Bido.':'Parlez-nous de votre besoin.'}</h1><p>{demo?'Présentez votre contexte de veille et de réponse. La démonstration sera centrée sur les usages les plus pertinents pour votre équipe.':'Question commerciale, support, partenariat, confidentialité ou problème de donnée : sélectionnez le bon motif et donnez-nous le contexte nécessaire.'}</p><div className="contact-points">{points.map(([Icon,title,text])=><div key={title}><Icon/><span><b>{title}</b>{text}</span></div>)}</div></div><ContactForm demo={demo}/></div></section></main>}

function About(){return <main id="main"><PageIntro eyebrow="À propos de Bido.ma" title="Rendre les marchés publics marocains plus lisibles et plus exploitables." text="Bido est né d’un constat simple : les entreprises ont besoin de transformer une information dispersée en un processus maîtrisé, depuis la veille jusqu’à la décision de répondre."/><section className="section"><div className="container about-grid"><div><div className="section-label">NOTRE MISSION</div><h2>Une technologie utile, ancrée dans les opérations des entreprises marocaines.</h2></div><div><p>Bido rapproche la recherche d’appels d’offres, la lecture documentaire, la qualification des opportunités, les agents IA et la collaboration d’équipe. La plateforme ne cherche pas à remplacer l’expertise métier : elle lui donne un cadre plus rapide, plus traçable et plus cohérent.</p><p>Notre vision est de faire de la veille marchés publics une capacité structurée plutôt qu’une succession de recherches manuelles. Nous développons le produit autour de quatre principes : clarté des sources, pertinence expliquée, responsabilité humaine et simplicité d’adoption.</p><p>Bido.ma est une entreprise technologique indépendante. Elle n’est affiliée à aucune autorité publique et ne se substitue ni aux documents officiels ni aux professionnels chargés de vérifier une candidature.</p></div></div><div className="container values-grid">{[['01','Clarté','Rendre les opportunités, documents et exigences plus faciles à comprendre.'],['02','Pertinence','Aider chaque entreprise à concentrer son attention sur les marchés publics cohérents avec son profil.'],['03','Responsabilité','Garder les sources, les limites de l’IA et la validation humaine visibles.']].map(([n,t,p])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{p}</p></article>)}</div></section><FinalCTA/></main>}

function Resources(){const cards=[['Guide','Structurer une veille marchés publics en 6 étapes','Une méthode pragmatique pour passer de la recherche quotidienne à un système de veille pilotable.'],['Qualification','Construire une grille Go / No-Go utile','Les critères à formaliser pour aligner intérêt commercial, capacité, risque et délai.'],['Méthode','Lire un dossier d’appel d’offres sans perdre le fil','Une séquence orientée exigences, preuves, responsabilités et vérification officielle.'],['IA responsable','Utiliser un analyseur IA de marchés publics avec contrôle','Les garde-fous essentiels pour exploiter l’IA sans déléguer la décision.'],['Checklist','Vérifier les documents exigés avant la préparation','Une liste de contrôle pour organiser les pièces administratives et techniques.'],['Organisation','Maîtriser les échéances d’un appel d’offres','Construire un calendrier interne avec marges, responsables et validations.'],['Recherche','Écrire une recherche d’appels d’offres plus précise','Combiner langage naturel, filtres avancés et recherche documentaire.'],['Pertinence','Comprendre le classement des opportunités','Utiliser un profil métier sans confondre pertinence et éligibilité.'],['Collaboration','Organiser un workflow d’équipe pour les marchés publics','Clarifier les rôles, statuts, décisions et prochaines actions.'],['Glossaire','Les termes essentiels des marchés publics','Un référentiel simple pour harmoniser le vocabulaire de l’équipe.']];return <main id="main"><PageIntro eyebrow="Ressources marchés publics" title="Des méthodes concrètes pour mieux rechercher, qualifier et répondre." text="Guides, checklists et décryptages en français pour les équipes commerciales, responsables appels d’offres, directions et experts métier."/><section className="section"><div className="container resource-grid">{cards.map(([type,title,text],i)=><article key={title}><div className={`resource-visual v${i%4}`}><ScrollIcon index={i}/><span>{type}</span></div><small>{type.toUpperCase()} · GUIDE PRATIQUE</small><h3>{title}</h3><p>{text}</p><Link href={i===0?'/ressources/veille-structuree':'/guides-marches-publics'}>Consulter cette ressource <ArrowRight/></Link></article>)}</div></section><FinalCTA/></main>}
function Blog(){const posts=[['Veille','Pourquoi une veille marchés publics doit commencer par un profil métier','Définir ce que votre entreprise recherche permet de réduire le bruit avant même l’analyse.'],['Recherche','Recherche en langage naturel ou filtres avancés : quand utiliser chaque méthode ?','Deux approches complémentaires pour explorer les appels d’offres et bons de commande.'],['Documents','Sept informations à vérifier dans un dossier d’appel d’offres','Un cadre de lecture pour repérer les conditions, dates, cautions, lots, pièces et livrables.'],['Qualification','Le score de pertinence ne remplace pas l’éligibilité','Comprendre la différence entre priorité commerciale et conformité aux conditions officielles.'],['IA','Comment interroger un marché public avec une IA sans perdre le contrôle','Des questions utiles, des sources visibles et une validation humaine systématique.'],['Organisation','Mettre en place une revue Go / No-Go courte et documentée','Un rituel pour décider plus tôt et conserver les raisons de chaque arbitrage.'],['Équipe','Qui doit intervenir dans la réponse à un appel d’offres ?','Répartir la veille, l’analyse, la validation et la préparation entre les bons rôles.'],['Confiance','Pourquoi les documents officiels restent toujours la référence','La place d’une plateforme indépendante face aux sources et responsabilités des utilisateurs.'],['Pilotage','Construire un tableau de bord de suivi des appels d’offres','Les statuts, dates et indicateurs nécessaires pour rendre le pipeline lisible.']];return <main id="main"><PageIntro eyebrow="Blog Bido" title="Comprendre les marchés publics, l’IA et les workflows de réponse." text="Analyses éditoriales et méthodes professionnelles pour améliorer la veille, la qualification et le suivi des opportunités publiques au Maroc."/><section className="section"><div className="container resource-grid">{posts.map(([type,title,text],i)=><article key={title}><div className={`resource-visual v${i%4}`}><ScrollIcon index={i+2}/><span>{type}</span></div><small>{type.toUpperCase()} · ARTICLE À VENIR</small><h3>{title}</h3><p>{text}</p><Link href={i===0?'/ressources/veille-structuree':'/ressources'}>Explorer les contenus associés <ArrowRight/></Link></article>)}</div></section><FinalCTA/></main>}
function ScrollIcon({index}){const Icons=[Search,Target,FileSearch,Sparkles,CheckCircle2,Globe2];const I=Icons[index%Icons.length];return <I/>}

function Article(){return <main id="main"><article className="article-page"><header><div className="section-label">GUIDE · 8 MIN DE LECTURE</div><h1>Structurer une veille marchés publics en 6 étapes</h1><p>Une méthode simple pour concentrer l’attention de votre équipe sur les opportunités à forte adéquation.</p><div className="byline"><span>BI</span><p><b>Équipe Bido</b><br/>Mis à jour en juillet 2026</p></div></header><div className="article-body"><aside><b>DANS CE GUIDE</b><a href="#profil">1. Définir le profil</a><a href="#signaux">2. Choisir les signaux</a><a href="#rituel">3. Installer un rituel</a></aside><div><p className="intro">Une veille performante n’est pas celle qui accumule le plus d’avis. C’est celle qui aide l’équipe à identifier tôt les dossiers compatibles avec sa stratégie et ses capacités.</p><h2 id="profil">1. Définir un profil d’opportunité explicite</h2><p>Commencez par formaliser les activités réellement maîtrisées, les zones servies, les ordres de grandeur acceptables et les contraintes qui constituent un motif d’exclusion.</p><blockquote>La pertinence vient d’un profil clair, pas d’une liste infinie de mots-clés.</blockquote><h2 id="signaux">2. Combiner plusieurs signaux</h2><p>Un secteur seul ne suffit pas. Croisez objet, acheteur, localisation, budget, délai et exigences de capacité pour construire une lecture plus robuste.</p><h2 id="rituel">3. Installer un rituel de qualification</h2><p>Prévoyez une revue courte et régulière. Chaque dossier doit avoir un responsable, un statut et une prochaine action documentée.</p><div className="article-cta"><h3>Transformez cette méthode en pipeline.</h3><p>Découvrez comment Bido structure la veille et la qualification.</p><Link className="button" href="/demo">Demander une démo <ArrowRight/></Link></div></div></div></article></main>}

function LegalPage({data}){return <main id="main"><PageIntro eyebrow="Confiance & transparence" title={data[0]} text={data[1]}/><section className="section legal-section"><div className="container"><div className="legal-alert"><ShieldCheck/><p><b>Document de pré-lancement.</b> Cette trame informative doit être complétée avec les informations légales de l’entreprise et validée par un professionnel compétent.</p></div>{data[2].map(([title,text],i)=><section key={title}><span>{String(i+1).padStart(2,'0')}</span><div><h2>{title}</h2><p>{text}</p></div></section>)}</div></section></main>}

function NotFound(){return <main id="main" className="not-found"><div><span>404</span><h1>Cette page n’est pas dans le dossier.</h1><p>Le lien demandé n’existe pas ou a été déplacé.</p><Link className="button" href="/">Retour à l’accueil <ArrowRight/></Link></div></main>}

function CookieBanner(){const [state,setState]=useState('loading');const [settings,setSettings]=useState(false);useEffect(()=>{setState(window.localStorage.getItem('bido-consent'))},[]);function choose(v){window.localStorage.setItem('bido-consent',v);setState(v);setSettings(false)}if(state==='loading'||state)return null;return <div className="cookie-banner"><Cookie/><div><b>Votre choix, avant toute mesure facultative.</b><p>Bido utilise uniquement les cookies nécessaires par défaut. Vous pouvez autoriser une future mesure d’audience anonyme.</p><button onClick={()=>setSettings(true)}>Personnaliser</button></div><div><button className="button outline" onClick={()=>choose('essential')}>Nécessaires seulement</button><button className="button" onClick={()=>choose('all')}>Tout accepter</button></div>{settings&&<div className="cookie-modal"><button className="modal-close" onClick={()=>setSettings(false)}><X/></button><h3>Préférences de cookies</h3><label><span><b>Cookies nécessaires</b><small>Fonctionnement et mémorisation du consentement.</small></span><input type="checkbox" checked disabled readOnly/></label><label><span><b>Mesure d’audience</b><small>Désactivée dans cette démonstration.</small></span><input type="checkbox"/></label><button className="button" onClick={()=>choose('essential')}>Enregistrer mes choix</button></div>}</div>}

function Footer(){return <footer><div className="container footer-main"><div className="footer-brand"><Logo light/><p>L’analyseur IA des marchés publics conçu pour aider les entreprises marocaines à rechercher, qualifier et suivre leurs opportunités.</p><span>Agadir · Maroc</span></div><div><b>Produit</b><Link href="/plateforme">Plateforme</Link><Link href="/opportunites">Marchés publics</Link><Link href="/analyseur-ia-marches-publics">Analyseur IA</Link><Link href="/recherche-documents-appels-offres">Documents</Link><Link href="/agents-ia">Agents IA</Link></div><div><b>Entreprise</b><Link href="/a-propos">À propos</Link><Link href="/ressources">Ressources</Link><Link href="/tarifs">Tarifs</Link><Link href="/contact">Contact</Link><Link href="/demo">Demander une démo</Link></div><div><b>Confiance</b><Link href="/securite">Sécurité</Link><Link href="/confidentialite">Confidentialité</Link><Link href="/conditions">Conditions</Link><Link href="/ia-responsable">IA responsable</Link><Link href="/sources">Sources</Link></div></div><div className="container disclaimer">Bido.ma est une plateforme technologique indépendante et n’est affiliée ni approuvée par aucune autorité publique. Vérifiez toujours les documents, échéances et exigences auprès des sources officielles.</div><div className="container footer-bottom"><span>© 2026 Bido.ma. Tous droits réservés.</span><div><Link href="/mentions-legales">Mentions légales</Link><button onClick={()=>{window.localStorage.removeItem('bido-consent');window.location.reload()}}>Gérer les cookies</button></div></div></footer>}

function PageContent({pathname,locale}){if(pathname==='/')return <Home locale={locale}/>;if(productPages[pathname])return <StandardPage data={productPages[pathname]}/>;if(solutionPages[pathname])return <SolutionPage data={solutionPages[pathname]}/>;if(legalPages[pathname])return <LegalPage data={legalPages[pathname]}/>;if(pathname==='/tarifs')return <Pricing/>;if(pathname==='/a-propos')return <About/>;if(pathname==='/contact')return <Contact/>;if(pathname==='/demo')return <Contact demo/>;if(pathname==='/faq')return <main id="main"><PageIntro eyebrow="FAQ marchés publics" title="Les questions importantes sur Bido, traitées clairement." text="Produit, sources, recherche, pertinence, intelligence artificielle, équipe, tarifs et confiance : retrouvez les réponses utiles avant de commencer."/><FAQBlock/></main>;if(pathname==='/ressources')return <Resources/>;if(pathname==='/blog')return <Blog/>;if(pathname==='/ressources/veille-structuree')return <Article/>;return <NotFound/>}

export default function App({initialPath='/'}){const [locale,setLocale]=useState('fr');const pathname=usePathname()||initialPath;useEffect(()=>{window.scrollTo(0,0)},[pathname]);useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dir=locale==='ar'?'rtl':'ltr'},[locale]);return <><Header locale={locale} setLocale={setLocale}/><PageContent pathname={pathname} locale={locale}/><Footer/><CookieBanner/></>}
