export const blogSlugs = ['reforme-marches-publics-2026', 'marches-btp-2026', 'ia-marches-publics'];

const shared = {
  reform: { slug: blogSlugs[0], image: '/blog/reforme-marches-publics-2026.webp', source: 'https://lopinion.ma/fr/actu-maroc/marches-publics--la-reforme-qui-change-les-regles-du-jeu_a32731?articleId=7341ce79-b6bd-4780-ae86-a15fe624c128' },
  btp: { slug: blogSlugs[1], image: '/blog/marches-btp-2026.webp', source: 'https://medias24.com/2026/04/08/routes-eau-ports-73-mmdh-de-marches-prevus-en-2026-1656233/' },
  ai: { slug: blogSlugs[2], image: '/blog/ia-marches-publics.webp', source: 'https://www.oecd.org/en/publications/digital-transformation-of-public-procurement_79651651-en.html' },
};

export const blogContent = {
  fr: {
    page: { label:'LE BLOG BIDO', title:'Comprendre le marché. Décider avec méthode.', text:'Analyses, données et méthodes concrètes pour les entreprises qui répondent aux marchés publics au Maroc.', featured:'À LA UNE', read:'Lire l’analyse', min:'8 min de lecture', all:'Toutes les analyses', team:'Équipe éditoriale Bido', updated:'Mis à jour le 15 juillet 2026', toc:'DANS CET ARTICLE', sources:'Sources et repères', sourceLabel:'Consulter la source', back:'Retour au blog', ctaTitle:'Transformez votre veille en décisions exploitables.', ctaText:'Bido détecte, qualifie et structure les opportunités qui correspondent réellement à votre entreprise.', cta:'Découvrir Bido' },
    articles: [
      { ...shared.reform, category:'RÉGLEMENTATION', title:'Réforme des marchés publics 2026 : ce qui pourrait changer pour les TPME', excerpt:'Accès des petites entreprises, préférence locale et encadrement des offres : les points à surveiller dans le projet de réforme.', lead:'Trois ans après le décret n° 2-22-431, un nouveau projet remet la commande publique au centre du débat. Pour les entreprises marocaines, l’enjeu n’est pas seulement juridique : il touche directement la capacité à accéder aux consultations, construire un prix soutenable et défendre une offre crédible.', quote:'Une réforme n’ouvre pas automatiquement le marché. Elle crée une fenêtre que les entreprises préparées savent transformer en opportunité.', key:'À retenir : le texte est encore présenté comme un projet soumis à consultation. Les mesures décrites doivent être vérifiées dans la version définitive avant toute décision.', sections:[
        ['Pourquoi cette réforme maintenant ?', 'La commande publique doit concilier trois objectifs parfois contradictoires : élargir la concurrence, protéger la qualité d’exécution et mieux maîtriser les budgets. Le projet annoncé en juillet 2026 cherche notamment à faciliter l’accès des TPME et des entreprises locales tout en renforçant l’encadrement des offres financières.', ['Ne pas confondre projet et droit en vigueur','Identifier les mesures qui affectent votre secteur','Préparer les justificatifs avant la publication finale']],
        ['Ce que les TPME doivent surveiller', 'Les modalités d’accès, les critères territoriaux, les exigences de chiffre d’affaires et la manière de comparer les prix peuvent modifier la stratégie de candidature. Une entreprise doit suivre le texte final, mais aussi les règlements de consultation qui traduiront concrètement ces principes.', ['Capacité financière demandée','Références techniques proportionnées','Part réservée ou accès facilité','Traitement des offres très basses']],
        ['Préparer une réponse plus robuste', 'La meilleure préparation consiste à documenter dès maintenant ses capacités, ses références et ses coûts réels. Une grille go / no-go doit distinguer l’éligibilité, la capacité d’exécution, le risque contractuel et l’intérêt commercial.', ['Mettre à jour les dossiers administratifs','Créer une bibliothèque de références vérifiables','Calculer un prix plancher soutenable','Conserver la trace de chaque décision']],
        ['Le rôle d’une veille structurée', 'Une réforme augmente souvent le nombre d’informations à suivre. Centraliser les avis, qualifier les acheteurs et comparer les exigences permet d’éviter une veille dispersée. Bido transforme ces signaux en une liste priorisée et expliquée.']
      ]},
      { ...shared.btp, category:'DONNÉES & MARCHÉ', title:'73 milliards de DH de marchés BTP en 2026 : où sont les opportunités ?', excerpt:'Équipements publics, routes, eau et ports : une lecture opérationnelle du programme d’investissement annoncé pour 2026.', lead:'Le programme prévisionnel présenté pour 2026 atteint 73 milliards de dirhams. Ce chiffre impressionne, mais il ne suffit pas pour décider où prospecter. L’essentiel est de lire sa répartition, d’identifier les maîtres d’ouvrage pertinents et de rapprocher chaque segment des capacités réelles de l’entreprise.', quote:'Le volume du marché indique où regarder. Votre capacité, vos références et votre territoire indiquent où répondre.', key:'Le programme annoncé se répartit principalement entre 28,8 MMDH d’équipements publics, 21,8 MMDH de routes et autoroutes, 18,3 MMDH pour l’eau et la météorologie, et 4 MMDH pour le portuaire et le maritime.', sections:[
        ['Quatre pôles concentrent l’investissement', 'Les équipements publics arrivent en tête, suivis des infrastructures routières, du secteur de l’eau et enfin des projets portuaires. Cette structure ouvre des marchés directs de travaux, mais aussi des missions d’études, de contrôle, de fourniture, de maintenance et d’assistance technique.', ['28,8 MMDH — équipements publics','21,8 MMDH — routes et autoroutes','18,3 MMDH — eau et météorologie','4 MMDH — ports et maritime']],
        ['Eau et résilience : une chaîne d’opportunités', 'Barrages, alimentation en eau potable rurale, protection contre les inondations et équipements hydromécaniques mobilisent des compétences très différentes. Les bureaux d’études, entreprises de travaux, fournisseurs et laboratoires doivent donc construire des veilles distinctes.', ['Études hydrauliques et topographiques','Conduites, ouvrages et stations de pompage','Équipements électromécaniques','Contrôle, essais et suivi']],
        ['Transformer une annonce en pipeline', 'Un programme prévisionnel n’est pas encore un appel d’offres. Il sert à préparer les partenariats, vérifier les qualifications, suivre les acheteurs et anticiper les besoins de trésorerie. Chaque opportunité doit ensuite être qualifiée à partir du dossier officiel.', ['Cartographier les donneurs d’ordres','Créer une veille par métier et par région','Vérifier les références et classes requises','Planifier les groupements éventuels']],
        ['La méthode Bido', 'Bido rapproche les opportunités de votre profil, signale les échéances et structure le travail de qualification. L’objectif n’est pas de recevoir plus d’avis, mais de voir plus tôt ceux sur lesquels votre équipe peut réellement agir.']
      ]},
      { ...shared.ai, category:'INTELLIGENCE ARTIFICIELLE', title:'IA et marchés publics : 7 tâches à accélérer, 5 décisions à garder humaines', excerpt:'Une méthode responsable pour gagner du temps sur les dossiers sans déléguer le jugement professionnel à une machine.', lead:'L’intelligence artificielle peut réduire le temps consacré au tri, à l’extraction et à la première lecture des dossiers. Elle ne doit pourtant ni inventer une exigence, ni valider seule une candidature, ni engager l’entreprise sur un prix ou un délai.', quote:'L’IA assiste la lecture. La source fait foi. L’équipe décide.', key:'Une utilisation responsable impose trois garde-fous : relier chaque information à sa source, rendre visibles les incertitudes et exiger une validation humaine avant toute décision engageante.', sections:[
        ['Sept tâches que l’IA peut accélérer', 'L’IA est utile lorsque le travail est répétitif, volumineux et vérifiable. Elle peut classer les opportunités, extraire les dates, repérer les conditions d’éligibilité, résumer les pièces, signaler les incohérences, comparer le dossier au profil de l’entreprise et préparer une checklist.', ['Classer les avis','Extraire dates et montants','Repérer les critères d’éligibilité','Résumer sans masquer la source','Comparer au profil entreprise','Signaler les points d’attention','Préparer la checklist']],
        ['Cinq décisions qui restent humaines', 'La décision finale demande du contexte, de la responsabilité et souvent un arbitrage entre plusieurs risques. L’éligibilité juridique, l’engagement technique, le prix final, l’acceptation du risque contractuel et l’autorisation de dépôt restent sous contrôle humain.', ['Validation juridique','Engagement technique','Prix et marge','Acceptation des risques','Approbation du dépôt']],
        ['Un workflow vérifiable', 'Chaque réponse générée doit pointer vers la page ou la clause d’origine. Les informations sensibles doivent être relues, et les versions du dossier doivent rester identifiables. Une synthèse sans source est une piste, jamais une preuve.', ['Source visible','Niveau de confiance explicite','Validation assignée','Historique conservé']],
        ['Ce que Bido cherche à améliorer', 'Bido organise la collaboration entre la machine et l’expert : l’outil fait remonter les éléments utiles, tandis que l’équipe conserve le contrôle, documente son analyse et décide avec une information mieux structurée.']
      ]}
    ]
  },
  en: {
    page:{ label:'THE BIDO BLOG', title:'Understand the market. Decide methodically.', text:'Analysis, data and practical methods for companies pursuing public contracts in Morocco.', featured:'FEATURED', read:'Read analysis', min:'8 min read', all:'All insights', team:'Bido editorial team', updated:'Updated July 15, 2026', toc:'IN THIS ARTICLE', sources:'Sources and references', sourceLabel:'View source', back:'Back to blog', ctaTitle:'Turn monitoring into actionable decisions.', ctaText:'Bido detects, qualifies and structures opportunities that genuinely fit your business.', cta:'Discover Bido' },
    articles: []
  },
  ar: {
    page:{ label:'مدونة Bido', title:'افهم السوق واتخذ القرار بمنهجية.', text:'تحليلات وبيانات ومنهجيات عملية للمقاولات المهتمة بالصفقات العمومية في المغرب.', featured:'موضوع مميز', read:'اقرأ التحليل', min:'8 دقائق للقراءة', all:'جميع التحليلات', team:'فريق تحرير Bido', updated:'آخر تحديث: 15 يوليوز 2026', toc:'في هذا المقال', sources:'المصادر والمراجع', sourceLabel:'اطلع على المصدر', back:'العودة إلى المدونة', ctaTitle:'حوّل الرصد إلى قرارات قابلة للتنفيذ.', ctaText:'تكتشف Bido الفرص الملائمة لمقاولتكم وتؤهلها وتنظمها.', cta:'اكتشف Bido' },
    articles: []
  }
};

blogContent.en.articles = [
  { ...shared.reform, category:'REGULATION', title:'Morocco’s 2026 public procurement reform: what could change for SMEs', excerpt:'SME access, local preference and tighter bid controls: the points businesses should monitor in the proposed reform.', lead:'Three years after Decree 2-22-431, a new proposal has put public procurement back in focus. For Moroccan businesses, the issue is operational as well as legal: access to tenders, sustainable pricing and the ability to defend a credible bid.', quote:'Reform does not automatically open a market. It creates a window that prepared businesses can turn into opportunity.', key:'Important: the measures discussed are still presented as a proposal under consultation. Verify the final published text before making any legal or commercial decision.', sections:[['Why reform now?','Public procurement must widen competition, protect delivery quality and control budgets. The proposal reported in July 2026 aims to improve access for SMEs and local companies while strengthening oversight of financial bids.',['Distinguish proposals from current law','Identify measures affecting your sector','Prepare evidence before final publication']],['What SMEs should monitor','Access rules, territorial criteria, turnover requirements and price-comparison methods may change bidding strategies. The final rules and each consultation document will determine the practical effect.',['Financial capacity','Proportionate references','Facilitated SME access','Treatment of unusually low bids']],['Build a stronger response','Document capabilities, references and real costs now. A go/no-go framework should separate eligibility, delivery capacity, contractual risk and commercial value.',['Update administrative files','Build a verifiable reference library','Calculate a sustainable price floor','Document every decision']],['Why structured monitoring matters','Regulatory change increases the signals teams must follow. Centralised monitoring helps compare buyers, requirements and deadlines without losing focus.']]},
  { ...shared.btp, category:'DATA & MARKET', title:'MAD 73 billion in 2026 construction contracts: where are the opportunities?', excerpt:'Public facilities, roads, water and ports: an operational reading of Morocco’s announced 2026 investment programme.', lead:'The provisional programme announced for 2026 reaches MAD 73 billion. The headline is significant, but useful decisions require looking at the breakdown, relevant contracting authorities and the fit with each company’s actual capabilities.', quote:'Market volume tells you where to look. Capability, references and territory tell you where to bid.', key:'The announced programme includes MAD 28.8bn for public facilities, MAD 21.8bn for roads and motorways, MAD 18.3bn for water and meteorology, and MAD 4bn for ports and maritime works.', sections:[['Four investment clusters','Public facilities lead, followed by roads, water and ports. Beyond construction, this creates demand for design, supervision, supplies, maintenance and technical assistance.',['MAD 28.8bn — public facilities','MAD 21.8bn — roads','MAD 18.3bn — water','MAD 4bn — ports']],['Water and resilience','Dams, rural drinking water, flood protection and hydromechanical equipment require distinct capabilities and separate monitoring profiles.',['Hydraulic and surveying studies','Pipelines and pumping stations','Electromechanical equipment','Testing and supervision']],['From announcement to pipeline','A provisional programme is not a tender. Use it to prepare partnerships, qualifications and cash-flow capacity, then assess each opportunity from its official documents.',['Map contracting authorities','Monitor by trade and region','Verify required references','Plan possible consortiums']],['The Bido method','Bido matches opportunities to your profile, flags deadlines and structures qualification work. The goal is not more notices; it is earlier visibility on opportunities your team can act on.']]},
  { ...shared.ai, category:'ARTIFICIAL INTELLIGENCE', title:'AI and public procurement: 7 tasks to accelerate, 5 decisions to keep human', excerpt:'A responsible method for saving time on tender files without delegating professional judgment to a machine.', lead:'Artificial intelligence can reduce time spent sorting, extracting and performing a first reading. It must not invent requirements, independently validate eligibility or commit a company to a price or deadline.', quote:'AI assists the reading. The source prevails. The team decides.', key:'Responsible use requires three safeguards: connect information to its source, expose uncertainty and require human approval before consequential decisions.', sections:[['Seven tasks AI can accelerate','AI works best on repetitive, high-volume and verifiable work: classification, date extraction, eligibility detection, summarisation, inconsistency flags, company-fit comparison and checklist preparation.',['Classify notices','Extract dates and amounts','Detect eligibility criteria','Summarise with sources','Compare company fit','Flag attention points','Prepare checklists']],['Five decisions stay human','Final decisions require context and accountability. Legal eligibility, technical commitments, final price, contractual risk and submission approval remain human responsibilities.',['Legal validation','Technical commitment','Price and margin','Risk acceptance','Submission approval']],['A verifiable workflow','Generated answers should point to the original page or clause. Sensitive information must be reviewed and document versions must remain identifiable.',['Visible source','Explicit confidence','Assigned validation','Preserved history']],['What Bido improves','Bido organises collaboration between software and experts: the tool surfaces useful information while the team retains control, documents its reasoning and decides from better-structured evidence.']]}
];

blogContent.ar.articles = [
  { ...shared.reform, category:'التنظيم', title:'إصلاح الصفقات العمومية 2026: ما الذي قد يتغير بالنسبة للمقاولات الصغرى والمتوسطة؟', excerpt:'ولوج المقاولات الصغرى، والأفضلية المحلية، وتأطير العروض المالية: أهم النقاط التي ينبغي تتبعها في مشروع الإصلاح.', lead:'بعد ثلاث سنوات من المرسوم رقم 2-22-431، أعاد مشروع جديد الصفقات العمومية إلى صدارة النقاش. ولا يقتصر أثره المحتمل على الجانب القانوني، بل يشمل قدرة المقاولات على الولوج إلى المنافسات وبناء سعر قابل للتنفيذ والدفاع عن عرض موثوق.', quote:'لا يفتح الإصلاح السوق تلقائياً، لكنه يخلق فرصة تستطيع المقاولات المستعدة تحويلها إلى نتائج.', key:'مهم: ما زالت المقتضيات المذكورة مقدمة باعتبارها مشروعاً قيد التشاور. يجب الرجوع إلى النص النهائي المنشور قبل اتخاذ أي قرار قانوني أو تجاري.', sections:[['لماذا يُطرح الإصلاح الآن؟','تحتاج الصفقات العمومية إلى توسيع المنافسة وحماية جودة التنفيذ وضبط الميزانيات. ويهدف المشروع المعلن في يوليوز 2026 إلى تسهيل ولوج المقاولات الصغرى والمحلية مع تعزيز تأطير العروض المالية.',['التمييز بين المشروع والقانون الجاري','تحديد المقتضيات المؤثرة في قطاعكم','إعداد الوثائق قبل صدور النص النهائي']],['ما الذي ينبغي للمقاولات تتبعه؟','قد تؤثر شروط الولوج والمعايير الترابية ومتطلبات رقم المعاملات وطريقة مقارنة الأسعار في استراتيجية المشاركة. ويبقى النص النهائي ونظام كل استشارة هما المرجع العملي.',['القدرة المالية المطلوبة','تناسب المراجع التقنية','تسهيل ولوج المقاولات الصغرى','معالجة العروض المنخفضة جداً']],['إعداد عرض أكثر متانة','ابدؤوا بتوثيق القدرات والمراجع والتكاليف الحقيقية. ويجب أن تميز شبكة قرار المشاركة بين الأهلية والقدرة على التنفيذ والمخاطر التعاقدية والقيمة التجارية.',['تحيين الملف الإداري','إنشاء مكتبة مراجع قابلة للتحقق','حساب حد أدنى مستدام للسعر','توثيق كل قرار']],['أهمية الرصد المنظم','تزيد الإصلاحات عدد الإشارات الواجب تتبعها. ويساعد الرصد المركزي على مقارنة أصحاب المشاريع والشروط والآجال دون تشتيت انتباه الفريق.']]},
  { ...shared.btp, category:'بيانات السوق', title:'73 مليار درهم من صفقات البناء في 2026: أين توجد الفرص؟', excerpt:'التجهيزات العمومية والطرق والماء والموانئ: قراءة عملية لبرنامج الاستثمار المعلن لسنة 2026.', lead:'يبلغ البرنامج التوقعي المعلن لسنة 2026 نحو 73 مليار درهم. لكن الرقم الإجمالي لا يكفي لاتخاذ القرار؛ إذ ينبغي فهم توزيعه وتحديد أصحاب المشاريع الملائمين وربط كل مجال بالقدرات الحقيقية للمقاولة.', quote:'حجم السوق يحدد أين تبحثون، أما القدرات والمراجع والمجال الترابي فتحدد أين تشاركون.', key:'يتوزع البرنامج المعلن أساساً على 28.8 مليار درهم للتجهيزات العمومية، و21.8 ملياراً للطرق، و18.3 ملياراً للماء والأرصاد الجوية، و4 مليارات للموانئ والقطاع البحري.', sections:[['أربعة مجالات تستقطب الاستثمار','تتصدر التجهيزات العمومية، تليها الطرق ثم الماء والموانئ. ولا تقتصر الفرص على الأشغال، بل تشمل الدراسات والمراقبة والتوريد والصيانة والمساعدة التقنية.',['28.8 مليار — تجهيزات عمومية','21.8 مليار — طرق','18.3 مليار — ماء','4 مليارات — موانئ']],['الماء والقدرة على الصمود','تتطلب السدود والماء الصالح للشرب والحماية من الفيضانات والتجهيزات الهيدروميكانيكية كفاءات مختلفة وملفات رصد مستقلة.',['دراسات هيدروليكية وطبوغرافية','قنوات ومحطات ضخ','تجهيزات كهروميكانيكية','مراقبة واختبارات وتتبع']],['من الإعلان إلى محفظة الفرص','البرنامج التوقعي ليس إعلاناً عن طلب عروض. استعملوه لإعداد الشراكات والتحقق من المؤهلات والقدرة المالية، ثم قيّموا كل فرصة انطلاقاً من ملفها الرسمي.',['رسم خريطة أصحاب المشاريع','رصد حسب المهنة والجهة','التحقق من المراجع المطلوبة','التخطيط للتجمعات المحتملة']],['منهجية Bido','تطابق Bido الفرص مع ملف مقاولتكم، وتبرز الآجال وتنظم التأهيل. الهدف ليس تلقي إعلانات أكثر، بل اكتشاف الفرص القابلة للتنفيذ في وقت أبكر.']]},
  { ...shared.ai, category:'الذكاء الاصطناعي', title:'الذكاء الاصطناعي والصفقات العمومية: 7 مهام للتسريع و5 قرارات تبقى بشرية', excerpt:'منهج مسؤول لتوفير الوقت في تحليل الملفات دون تفويض الحكم المهني للآلة.', lead:'يمكن للذكاء الاصطناعي تقليص الوقت المخصص للفرز والاستخراج والقراءة الأولية. لكنه لا ينبغي أن يخترع شرطاً أو يثبت الأهلية بمفرده أو يلزم المقاولة بسعر أو أجل.', quote:'الذكاء الاصطناعي يساعد على القراءة، والمصدر هو المرجع، والفريق هو صاحب القرار.', key:'يفرض الاستخدام المسؤول ثلاثة ضوابط: ربط كل معلومة بمصدرها، وإظهار درجة عدم اليقين، واشتراط المصادقة البشرية قبل القرارات الملزمة.', sections:[['سبع مهام يمكن تسريعها','يكون الذكاء الاصطناعي مفيداً في العمل المتكرر والكثيف والقابل للتحقق، مثل التصنيف واستخراج التواريخ ورصد شروط الأهلية والتلخيص وكشف التناقضات والمقارنة وإعداد قوائم التحقق.',['تصنيف الإعلانات','استخراج التواريخ والمبالغ','رصد شروط الأهلية','تلخيص مرتبط بالمصادر','المقارنة مع ملف المقاولة','إبراز نقاط الانتباه','إعداد قائمة التحقق']],['خمسة قرارات تبقى بشرية','تتطلب القرارات النهائية سياقاً ومسؤولية. لذلك تبقى الأهلية القانونية والالتزام التقني والسعر النهائي وقبول المخاطر والمصادقة على الإيداع بيد الفريق.',['المصادقة القانونية','الالتزام التقني','السعر والهامش','قبول المخاطر','الموافقة على الإيداع']],['مسار قابل للتحقق','يجب أن تشير كل إجابة إلى الصفحة أو البند الأصلي، وأن تُراجع المعلومات الحساسة، وأن تظل نسخ الوثائق قابلة للتحديد.',['مصدر ظاهر','درجة ثقة واضحة','مصادقة مسندة','سجل محفوظ']],['ما الذي تحسنه Bido؟','تنظم Bido التعاون بين الأداة والخبير: تبرز المنصة المعلومات المفيدة، بينما يحتفظ الفريق بالتحكم ويوثق تحليله ويتخذ القرار بناءً على أدلة أكثر تنظيماً.']]}
];

export function findBlogArticle(locale, slug) { return blogContent[locale]?.articles.find((article) => article.slug === slug); }
