'use client';

import Link from 'next/link';
import { ArrowLeft, ArrowRight, CalendarDays, Clock3, ExternalLink, Quote, Sparkles } from 'lucide-react';
import { blogContent, findBlogArticle } from './blog-content';
import { localizedHref } from './localized-content';
import { company } from './config';

export function BlogIndex({ locale='fr' }) {
  const { page:p, articles }=blogContent[locale]; const [featured,...rest]=articles;
  return <main id="main" className="blog-page"><section className="blog-hero"><div className="blueprint"/><div className="container"><div className="eyebrow"><span/><b>{p.label}</b></div><h1>{p.title}</h1><p>{p.text}</p></div></section><section className="blog-listing"><div className="container"><Link className="featured-story" href={localizedHref(locale,`/blog/${featured.slug}`)}><div className="story-image"><img src={featured.image} alt=""/><span>{p.featured}</span></div><div className="story-copy"><small>{featured.category}</small><h2>{featured.title}</h2><p>{featured.excerpt}</p><div className="story-meta"><span><CalendarDays/>15.07.2026</span><span><Clock3/>{p.min}</span></div><b>{p.read}<ArrowRight/></b></div></Link><div className="blog-section-title"><span>{p.all}</span><i/></div><div className="blog-grid">{rest.map(a=><article key={a.slug}><Link className="blog-card-image" href={localizedHref(locale,`/blog/${a.slug}`)}><img src={a.image} alt=""/></Link><small>{a.category}</small><h2><Link href={localizedHref(locale,`/blog/${a.slug}`)}>{a.title}</Link></h2><p>{a.excerpt}</p><div><span><Clock3/>{p.min}</span><Link href={localizedHref(locale,`/blog/${a.slug}`)} aria-label={p.read}><ArrowRight/></Link></div></article>)}</div></div></section></main>;
}

export function BlogArticle({ locale='fr', slug }) {
  const { page:p, articles }=blogContent[locale]; const a=findBlogArticle(locale,slug); if(!a)return null;
  const others=articles.filter(x=>x.slug!==slug);
  return <main id="main"><article className="editorial-article"><header className="editorial-header"><div className="container"><Link className="back-blog" href={localizedHref(locale,'/blog')}><ArrowLeft/>{p.back}</Link><div className="article-kicker">{a.category}</div><h1>{a.title}</h1><p>{a.excerpt}</p><div className="editorial-meta"><span className="author-mark">BI</span><span><b>{p.team}</b><small>{p.updated}</small></span><i/><span><Clock3/>{p.min}</span></div></div></header><div className="article-cover container"><img src={a.image} alt={a.title}/><span>© Bido.ma · 2026</span></div><div className="editorial-layout container"><aside><b>{p.toc}</b>{a.sections.map(([title],i)=><a key={title} href={`#section-${i+1}`}>{String(i+1).padStart(2,'0')} — {title}</a>)}</aside><div className="editorial-content"><p className="article-lead">{a.lead}</p><div className="key-takeaway"><Sparkles/><p>{a.key}</p></div>{a.sections.map(([title,text,points],i)=><section id={`section-${i+1}`} key={title}><span className="section-number">0{i+1}</span><h2>{title}</h2><p>{text}</p>{points&&<ul>{points.map(point=><li key={point}>{point}</li>)}</ul>}{i===0&&<blockquote><Quote/><p>{a.quote}</p></blockquote>}</section>)}<div className="article-sources"><h3>{p.sources}</h3><a href={a.source} target="_blank" rel="noreferrer">{p.sourceLabel}<ExternalLink/></a></div><div className="blog-inline-cta"><h3>{p.ctaTitle}</h3><p>{p.ctaText}</p><Link className="button white" href={company.appUrl}>{p.cta}<ArrowRight/></Link></div></div></div></article><section className="related-posts"><div className="container"><div className="blog-section-title"><span>{p.all}</span><i/></div><div className="related-grid">{others.map(x=><Link href={localizedHref(locale,`/blog/${x.slug}`)} key={x.slug}><img src={x.image} alt=""/><span>{x.category}</span><h3>{x.title}</h3></Link>)}</div></div></section></main>;
}
