import {
  BellRing, Binoculars, Bot, BriefcaseBusiness, Building2, ChartNoAxesCombined,
  CheckCheck, CircleGauge, FileCheck2, FileStack, Fingerprint, GitCompareArrows,
  Landmark, Layers3, LockKeyhole, MessagesSquare, Radar, ScrollText, SearchCheck,
  ShieldCheck, Sparkles, UsersRound, Workflow,
} from 'lucide-react';

export const company = {
  name: 'Bido', domain: 'bido.ma', email: 'contact@bido.ma', support: 'support@bido.ma',
  phone: '+212 5 XX XX XX XX', city: 'Agadir, Maroc',
  loginUrl: '#', signupUrl: '/demo', statusUrl: '#',
};

export const productPages = {
  '/plateforme': { eyebrow: 'La plateforme', title: 'Un poste de pilotage pour vos marchés publics', text: 'Centralisez la veille, l’analyse, la qualification et la préparation dans un environnement conçu pour les équipes marocaines.', icon: CircleGauge, metrics: [['1 espace', 'pour tout le pipeline'], ['3 langues', 'FR · AR · EN'], ['24/7', 'veille configurable']], features: [['Un pipeline lisible', 'Passez d’une opportunité détectée à une décision documentée.'], ['Une base de connaissance', 'Conservez documents, analyses, commentaires et arbitrages.'], ['Une exécution homogène', 'Standardisez les méthodes sans rigidifier les équipes.']] },
  '/opportunites': { eyebrow: 'Opportunity discovery', title: 'Repérez les opportunités qui méritent votre attention', text: 'Transformez une masse d’avis hétérogènes en une sélection exploitable, alignée sur vos métiers, territoires et capacités.', icon: Radar, metrics: [['Multi-critères', 'mots-clés et secteurs'], ['Alertes', 'selon vos priorités'], ['Listes', 'partagées en équipe']], features: [['Recherche structurée', 'Filtrez par secteur, acheteur, territoire, budget et échéance.'], ['Profils de pertinence', 'Formalisez ce qui constitue une bonne opportunité pour votre entreprise.'], ['Veilles enregistrées', 'Retrouvez vos recherches et recevez les nouveautés utiles.']] },
  '/analyse-appels-offres': { eyebrow: 'Tender intelligence', title: 'Comprenez plus vite. Décidez avec méthode.', text: 'Synthétisez les points critiques d’un dossier et structurez la décision go / no-go avec des éléments vérifiables.', icon: SearchCheck, metrics: [['Synthèse', 'orientée décision'], ['Risques', 'rendus visibles'], ['Go / No-go', 'traçable']], features: [['Lecture dirigée', 'Faites ressortir objets, exigences, délais et points d’attention.'], ['Grille de qualification', 'Comparez l’opportunité à vos capacités et priorités.'], ['Journal de décision', 'Conservez les raisons, réserves et validations internes.']] },
  '/analyse-documents': { eyebrow: 'Document intelligence', title: 'Des dossiers volumineux aux informations actionnables', text: 'Interrogez vos pièces, localisez les clauses importantes et construisez des checklists à partir des documents sources.', icon: FileStack, metrics: [['PDF', 'lecture assistée'], ['Clauses', 'repérage ciblé'], ['Checklist', 'préparation guidée']], features: [['Analyse contextualisée', 'Posez des questions ancrées dans le contenu de vos pièces.'], ['Extraction structurée', 'Organisez dates, montants, critères et livrables.'], ['Traçabilité', 'Revenez toujours au document source avant de décider.']] },
  '/agents-ia': { eyebrow: 'Agents configurables', title: 'Des assistants IA cadrés par vos processus', text: 'Configurez des agents spécialisés pour surveiller, analyser, comparer ou préparer — avec des règles, sources et limites explicites.', icon: Bot, metrics: [['Rôles', 'configurables'], ['Sources', 'délimitées'], ['Validation', 'humaine']], features: [['Agent de veille', 'Surveille des périmètres et prépare une sélection.'], ['Agent analyste', 'Applique votre grille de lecture à chaque dossier.'], ['Agent préparateur', 'Structure les actions et pièces attendues sans remplacer vos experts.']] },
  '/collaboration': { eyebrow: 'Travail en équipe', title: 'Une décision partagée, sans perdre le fil', text: 'Attribuez les responsabilités, centralisez les observations et conservez une chronologie claire de chaque dossier.', icon: UsersRound, metrics: [['Rôles', 'et responsabilités'], ['Notes', 'centralisées'], ['Historique', 'des décisions']], features: [['Espaces partagés', 'Regroupez l’équipe autour du même dossier.'], ['Actions assignées', 'Clarifiez qui prépare, vérifie et valide.'], ['Contexte durable', 'Évitez que l’information reste dispersée dans les messages.']] },
  '/alertes': { eyebrow: 'Monitoring', title: 'Restez en avance sur les échéances', text: 'Organisez une veille utile et des rappels contextualisés, sans ajouter davantage de bruit à vos journées.', icon: BellRing, metrics: [['Alertes', 'personnalisées'], ['Échéances', 'suivies'], ['Digest', 'synthétique']], features: [['Règles de veille', 'Choisissez secteurs, zones, acheteurs et mots-clés.'], ['Calendrier critique', 'Visualisez les jalons qui demandent une action.'], ['Notifications utiles', 'Priorisez ce qui mérite réellement une intervention.']] },
  '/reporting': { eyebrow: 'Reporting & exports', title: 'Rendez le pipeline visible aux décideurs', text: 'Suivez la couverture, la qualité du pipeline et les arbitrages à travers des vues synthétiques et exportables.', icon: ChartNoAxesCombined, metrics: [['Pipeline', 'consolidé'], ['Exports', 'opérationnels'], ['Suivi', 'des décisions']], features: [['Tableaux de bord', 'Lisez volumes, statuts, secteurs et échéances.'], ['Exports propres', 'Partagez des listes structurées avec les parties prenantes.'], ['Revue d’activité', 'Animez un rituel commercial fondé sur les mêmes données.']] },
  '/integrations': { eyebrow: 'Intégrations', title: 'Bido s’insère dans votre environnement de travail', text: 'Connectez progressivement les canaux et outils qui font circuler vos informations — sans complexifier le démarrage.', icon: Workflow, metrics: [['Email', 'notifications'], ['Exports', 'CSV · PDF'], ['API', 'sur étude']], features: [['Messagerie', 'Recevez alertes et synthèses dans vos canaux habituels.'], ['Données', 'Exportez les listes pour vos traitements internes.'], ['Sur mesure', 'Étudions les intégrations adaptées aux environnements avancés.']] },
  '/securite': { eyebrow: 'Sécurité & confiance', title: 'La confiance se construit par des contrôles concrets', text: 'Bido adopte une approche de sécurité par conception, une séparation claire des accès et une IA soumise à validation humaine.', icon: ShieldCheck, metrics: [['Accès', 'par rôle'], ['Données', 'isolées'], ['IA', 'supervisée']], features: [['Contrôle d’accès', 'Limitez les informations et actions selon les responsabilités.'], ['Pratiques documentées', 'Centralisez les choix de sécurité et de conservation.'], ['Usage responsable', 'Présentez les résultats IA comme une assistance, jamais comme une vérité automatique.']] },
};

export const solutionPages = {
  '/solutions/pme': ['PME', 'Transformez une petite équipe en cellule de veille structurée', 'Réduisez la charge de recherche et concentrez vos ressources sur les dossiers réellement alignés.', BriefcaseBusiness],
  '/solutions/entreprises': ['Grandes entreprises', 'Unifiez la veille de plusieurs métiers et entités', 'Donnez aux directions une vision consolidée sans effacer l’autonomie opérationnelle.', Building2],
  '/solutions/bid-managers': ['Bid managers', 'Pilotez chaque candidature avec plus de continuité', 'Rassemblez les exigences, responsabilités, risques et décisions dans un dossier vivant.', FileCheck2],
  '/solutions/developpement-commercial': ['Business development', 'Alimentez un pipeline public qualifié', 'Détectez plus tôt les signaux utiles et préparez des arbitrages commerciaux plus nets.', Binoculars],
  '/solutions/consultants': ['Consultants', 'Industrialisez l’analyse sans banaliser votre expertise', 'Gagnez en cohérence dans vos livrables tout en maintenant votre jugement au centre.', Landmark],
  '/secteurs/btp': ['BTP & ingénierie', 'Lisez les projets avec une logique de capacité et de risque', 'Territoires, qualifications, moyens, délais et pièces : structurez les éléments qui font la différence.', Layers3],
  '/secteurs/it': ['IT & digital', 'Repérez les besoins numériques adaptés à votre offre', 'Suivez les consultations en logiciels, infrastructure, services et transformation digitale.', Sparkles],
  '/secteurs/services': ['Services aux entreprises', 'Donnez de la précision à votre veille multisectorielle', 'Nettoyage, maintenance, formation, conseil : filtrez les opportunités selon vos expertises.', GitCompareArrows],
  '/secteurs/fournitures': ['Fournitures & équipements', 'Mieux cibler les consultations à forte adéquation', 'Croisez familles d’achats, zones de livraison, volumes et contraintes administratives.', BriefcaseBusiness],
};

export const nav = [
  ['Produit', [['Vue d’ensemble','/plateforme'],['Opportunités','/opportunites'],['Analyse des dossiers','/analyse-appels-offres'],['Documents','/analyse-documents'],['Agents IA','/agents-ia'],['Collaboration','/collaboration'],['Alertes','/alertes'],['Reporting','/reporting'],['Sécurité','/securite']]],
  ['Solutions', [['PME','/solutions/pme'],['Entreprises','/solutions/entreprises'],['Bid managers','/solutions/bid-managers'],['Consultants','/solutions/consultants'],['BTP & ingénierie','/secteurs/btp']]],
  ['Tarifs','/tarifs'], ['Ressources','/ressources'], ['Entreprise','/a-propos'],
];

export const legalPages = {
  '/confidentialite': ['Politique de confidentialité', 'Cette page présente la structure de confidentialité prévue pour Bido. Elle devra être validée et complétée avant mise en production.', [['Données traitées','Les données de compte, d’usage et de contact sont limitées à ce qui est nécessaire au service.'],['Finalités et bases','Chaque traitement doit être rattaché à une finalité claire, une base appropriée et une durée définie.'],['Vos droits','Les modalités d’accès, de rectification, d’opposition et de suppression seront précisées avec le contact confidentialité.'],['Sous-traitants','La liste des prestataires et lieux de traitement sera documentée avant lancement.']]],
  '/conditions': ['Conditions d’utilisation', 'Ces conditions constituent une trame produit à faire relire par un conseil qualifié avant toute ouverture commerciale.', [['Objet du service','Bido fournit des outils de veille, d’organisation et d’assistance à l’analyse.'],['Responsabilités','L’utilisateur reste responsable de vérifier les sources officielles, critères, dates et modalités de dépôt.'],['Disponibilité','Les objectifs de service et modalités de support seront définis dans l’offre contractuelle.'],['Propriété intellectuelle','Les règles applicables aux contenus, données et résultats devront être précisées contractuellement.']]],
  '/cookies': ['Politique de cookies', 'Bido prévoit un mécanisme de consentement granulaire. Les cookies non essentiels restent désactivés avant votre choix.', [['Nécessaires','Ils assurent les fonctions essentielles et la mémorisation de vos préférences.'],['Mesure d’audience','Cette catégorie facultative aide à comprendre l’usage global du site.'],['Préférences','Elle mémorise des réglages complémentaires lorsque vous l’autorisez.'],['Gestion','Vous pouvez modifier votre choix depuis le lien Cookies en pied de page.']]],
  '/mentions-legales': ['Mentions légales', 'Les informations légales définitives doivent être fournies avant publication commerciale.', [['Éditeur','Raison sociale, forme juridique, capital et identifiants à compléter.'],['Siège social','Adresse officielle à compléter.'],['Directeur de publication','Identité à compléter.'],['Hébergement','Prestataire et coordonnées à compléter.']]],
  '/ia-responsable': ['Déclaration pour une IA responsable', 'L’IA de Bido est conçue comme une assistance opérationnelle soumise au jugement professionnel.', [['Supervision humaine','Les résultats importants doivent être revus avant toute décision ou soumission.'],['Transparence','L’interface distingue les contenus sources, les extractions et les synthèses générées.'],['Limites connues','Une réponse peut être incomplète ou erronée ; le document officiel reste la référence.'],['Amélioration','Les retours et incidents alimentent un processus de contrôle et d’amélioration.']]],
  '/sources': ['Sources et attribution', 'Bido organise des informations publiquement accessibles sans se substituer aux plateformes officielles.', [['Indépendance','Bido n’est affilié à aucune autorité publique et ne revendique aucune approbation institutionnelle.'],['Vérification','Les utilisateurs doivent contrôler les avis, pièces et délais auprès des sources officielles.'],['Actualisation','Une information agrégée peut évoluer ; l’horodatage et la source doivent guider la vérification.'],['Signalement','Un canal permettra de signaler une donnée inexacte ou obsolète.']]],
};

export const faq = [
  ['Bido est-il un portail public officiel ?', 'Non. Bido est une plateforme technologique indépendante et n’est affilié ou approuvé par aucune autorité publique.'],
  ['L’IA peut-elle décider à la place de mon équipe ?', 'Non. Elle accélère la lecture et la structuration ; vos experts gardent la validation et la décision.'],
  ['Quels types d’opportunités sont couverts ?', 'La couverture cible progressivement les avis et consultations utiles aux entreprises marocaines. Le périmètre exact sera documenté au lancement.'],
  ['Puis-je configurer mes secteurs et territoires ?', 'Oui. Les profils de veille sont pensés pour combiner activités, zones, mots-clés, acheteurs et critères internes.'],
  ['Comment sont traités mes documents ?', 'Les engagements précis de conservation, d’hébergement et de sécurité seront publiés dans la documentation contractuelle avant ouverture.'],
  ['Existe-t-il une offre pour plusieurs entités ?', 'Oui, l’offre Entreprise est prévue pour les organisations ayant des équipes, entités ou règles d’accès multiples.'],
];
