import {
  BellRing, Binoculars, Bot, BriefcaseBusiness, Building2, ChartNoAxesCombined,
  CheckCheck, CircleGauge, FileCheck2, FileStack, Fingerprint, GitCompareArrows,
  Landmark, Layers3, LockKeyhole, MessagesSquare, Radar, ScrollText, SearchCheck,
  ShieldCheck, Sparkles, UsersRound, Workflow,
} from 'lucide-react';

const page = (config) => ({
  metrics: [['Sources', 'reliées au contexte'], ['Analyse', 'assistée par IA'], ['Décision', 'validée par l’équipe']],
  ...config,
});

export const productPages = {
  '/plateforme': page({
    eyebrow: 'Logiciel de marchés publics',
    title: 'Pilotez vos marchés publics dans un seul espace de travail',
    seoTitle: 'Logiciel de marchés publics au Maroc',
    text: 'Bido réunit la veille des appels d’offres et bons de commande, la recherche, la qualification, l’analyse documentaire et le suivi d’équipe dans une plateforme conçue pour les entreprises marocaines.',
    icon: CircleGauge,
    metrics: [['1 espace', 'pour tout le cycle'], ['AO & BDC', 'dans un flux structuré'], ['Équipe', 'alignée sur les priorités']],
    features: [['Découvrir sans se disperser', 'Consultez un flux d’opportunités publiques organisé selon vos activités, régions et priorités.'], ['Qualifier avec une méthode commune', 'Appliquez un profil métier et une grille de lecture cohérente avant de mobiliser l’équipe.'], ['Suivre chaque décision', 'Conservez les documents, analyses, responsabilités, échéances et arbitrages au même endroit.']],
    sections: [
      ['De la veille à la décision', 'Bido n’est pas un simple moteur de recherche d’appels d’offres. La plateforme organise le travail qui commence lorsqu’une opportunité est détectée.', [['Flux centralisé', 'Retrouvez les appels d’offres et bons de commande dans une vue lisible.'], ['Dossier de travail', 'Rassemblez les informations, pièces disponibles, notes et actions liées à chaque opportunité.'], ['Pipeline partagé', 'Visualisez les opportunités à qualifier, en analyse, à valider ou à préparer.']]],
      ['Un profil adapté à votre entreprise', 'Décrivez vos métiers, secteurs, zones d’intervention, mots-clés et exclusions pour obtenir un classement plus pertinent.', [['Préférences métier', 'Formalisez les activités que vous souhaitez surveiller.'], ['Pertinence expliquée', 'Comprenez les éléments qui rapprochent une opportunité de votre profil.'], ['Contrôle humain', 'Le classement aide à prioriser ; il ne garantit jamais l’éligibilité.']]],
      ['Une plateforme qui reste gouvernable', 'Les rôles, espaces de travail et historiques permettent de développer l’usage sans perdre la maîtrise des données et des décisions.', [['Accès par rôle', 'Adaptez la visibilité et les actions aux responsabilités.'], ['Historique exploitable', 'Retrouvez les décisions et changements importants.'], ['Paramètres centralisés', 'Gérez l’organisation, les préférences et les règles de veille depuis un même cadre.']]],
    ],
  }),
  '/opportunites': page({
    eyebrow: 'Appels d’offres et bons de commande',
    title: 'Découvrez les opportunités de marchés publics qui correspondent à votre activité',
    seoTitle: 'Appels d’offres et marchés publics au Maroc',
    text: 'Explorez les appels d’offres et bons de commande au Maroc dans un flux actualisé, puis filtrez les résultats selon votre secteur, votre territoire et vos priorités commerciales.',
    icon: Radar,
    metrics: [['AO & BDC', 'réunis dans le flux'], ['Multi-critères', 'pour réduire le bruit'], ['Listes', 'pour organiser la veille']],
    features: [['Un flux plus lisible', 'Parcourez les opportunités par date, acheteur, région, ville, catégorie et type de procédure.'], ['Une recherche ciblée', 'Combinez texte, filtres et profil d’entreprise pour isoler les dossiers utiles.'], ['Une veille continue', 'Sauvegardez vos recherches et revenez rapidement aux opportunités prioritaires.']],
    sections: [
      ['Réduisez le temps consacré au tri', 'Une veille marchés publics efficace ne consiste pas à ouvrir davantage d’avis. Elle consiste à écarter plus vite le bruit et à approfondir les bonnes opportunités.', [['Navigation chronologique', 'Identifiez les publications récentes et les échéances proches.'], ['Vue par acheteur', 'Suivez les organismes qui publient des besoins liés à votre activité.'], ['Couverture territoriale', 'Concentrez la recherche sur les régions et villes que votre entreprise peut servir.']]],
      ['Comparez avant d’ouvrir le dossier', 'Chaque résultat présente les informations utiles à une première qualification : objet, acheteur, localisation, dates, budget disponible et documents associés.', [['Lecture rapide', 'Obtenez le contexte essentiel depuis la liste de résultats.'], ['Pertinence visible', 'Repérez les opportunités rapprochées de votre profil métier.'], ['Action immédiate', 'Sauvegardez, partagez ou ouvrez l’analyse détaillée.']]],
      ['Des données à vérifier à la source', 'Bido structure des informations publiques pour faciliter la veille. Les avis, pièces, délais et conditions doivent toujours être confirmés dans les documents officiels.', [['Lien vers la source', 'Revenez à la publication officielle lorsque cela est nécessaire.'], ['Horodatage', 'Identifiez la date de collecte ou de mise à jour disponible.'], ['Indépendance', 'Bido n’est affilié ni approuvé par aucune autorité publique.']]],
    ],
  }),
  '/recherche-intelligente-marches-publics': page({
    eyebrow: 'Recherche en langage naturel',
    title: 'Recherchez des marchés publics avec vos propres mots',
    seoTitle: 'Recherche intelligente des marchés publics au Maroc',
    text: 'Exprimez votre besoin en langage naturel. Bido interprète l’intention, recherche dans les données structurées et les documents disponibles, puis présente des résultats que vous pouvez affiner.',
    icon: SearchCheck,
    metrics: [['Langage naturel', 'pour formuler le besoin'], ['Filtres', 'pour garder le contrôle'], ['Résultats', 'reliés aux critères']],
    features: [['Une recherche plus naturelle', 'Écrivez « marchés de maintenance informatique à Casablanca » plutôt que de multiplier les champs.'], ['Une intention structurée', 'Bido identifie les notions de secteur, lieu, délai, type d’achat et autres critères utiles.'], ['Une recherche transparente', 'Consultez et modifiez les filtres interprétés avant d’exploiter les résultats.']],
    sections: [
      ['Passez de la question aux opportunités', 'La recherche IA accélère la formulation sans supprimer les filtres. Vous pouvez partir d’une phrase, puis préciser les critères proposés.', [['Exemple informatique', '« Marchés de maintenance informatique à Casablanca ».'], ['Exemple fournitures', '« Fourniture de mobilier avec délai supérieur à 20 jours ».'], ['Exemple formation', '« Bons de commande pour formation professionnelle ».']]],
      ['Combinez sens et précision', 'La recherche textuelle identifie l’intention, tandis que les filtres structurés encadrent la région, le budget, la procédure, les dates ou le statut.', [['Interprétation visible', 'Vérifiez les critères compris par le système.'], ['Ajustement manuel', 'Ajoutez, retirez ou corrigez un filtre.'], ['Recherche réutilisable', 'Enregistrez la combinaison pour votre veille future.']]],
      ['Cherchez au-delà du titre', 'Lorsqu’une pièce est disponible et exploitable, Bido peut rechercher une notion mentionnée dans le dossier même si elle n’apparaît pas dans l’intitulé.', [['Termes techniques', 'Repérez une qualification, une norme ou un livrable.'], ['Conditions administratives', 'Localisez les cautions, délais ou documents demandés.'], ['Source consultable', 'Ouvrez le passage ou la pièce à vérifier.']]],
    ],
  }),
  '/recherche-avancee-appels-offres': page({
    eyebrow: 'Recherche avancée',
    title: 'Filtrez les appels d’offres selon vos critères opérationnels',
    seoTitle: 'Recherche avancée d’appels d’offres au Maroc',
    text: 'Construisez une recherche précise à partir du type d’opportunité, de l’acheteur, du territoire, du budget, de la procédure, des lots, des documents et du niveau de pertinence.',
    icon: GitCompareArrows,
    metrics: [['Filtres', 'combinables'], ['Critères', 'visibles et modifiables'], ['Recherche', 'sauvegardable']],
    features: [['Ciblez le bon périmètre', 'Distinguez les appels d’offres, bons de commande, catégories, secteurs et statuts.'], ['Cadrez la faisabilité', 'Utilisez les dates, budgets, cautions, lots et documents comme critères de présélection.'], ['Réutilisez votre méthode', 'Sauvegardez la recherche pour la rouvrir ou la partager avec l’équipe.']],
    sections: [
      ['Tous les critères importants dans une même vue', 'La recherche avancée permet de construire un périmètre clair sans perdre la compréhension de la requête.', [['Opportunité', 'Type, mots-clés, catégorie, secteur, procédure et statut.'], ['Acheteur et territoire', 'Organisme, région et ville.'], ['Conditions', 'Dates, budget, lots, caution et présence de documents.']]],
      ['Affinez sans repartir de zéro', 'Les filtres actifs restent visibles. L’équipe peut retirer un critère trop restrictif, élargir une période ou ajuster un seuil.', [['Compteurs de résultats', 'Mesurez immédiatement l’effet d’un filtre.'], ['Tri configurable', 'Classez par date, échéance ou pertinence.'], ['Partage interne', 'Transmettez une vue cohérente à un collègue.']]],
      ['Transformez un filtre en veille', 'Une recherche utile peut devenir une liste de veille suivie dans le temps.', [['Nom explicite', 'Identifiez la recherche par secteur, client, région ou équipe.'], ['Fréquence choisie', 'Adaptez le rythme de consultation ou de notification.'], ['Nouveautés isolées', 'Repérez les opportunités ajoutées depuis la dernière revue.']]],
    ],
  }),
  '/recherche-documents-appels-offres': page({
    eyebrow: 'Recherche dans les documents',
    title: 'Recherchez ce qui est écrit dans le dossier, pas seulement dans le titre',
    seoTitle: 'Recherche dans les documents d’appels d’offres',
    text: 'Bido vous aide à localiser les critères techniques, exigences administratives, cautions, délais, lots, qualifications et livrables dans les avis et pièces disponibles.',
    icon: FileStack,
    metrics: [['Pièces', 'rattachées au dossier'], ['Passages', 'retrouvés par contexte'], ['Vérification', 'dans la source officielle']],
    features: [['Interrogez le contenu', 'Recherchez un terme, une exigence ou une question dans les documents accessibles.'], ['Repérez les passages utiles', 'Accédez au contexte associé plutôt qu’à une réponse isolée.'], ['Gardez la source au centre', 'Vérifiez toute information importante dans la pièce officielle.']],
    sections: [
      ['Retrouvez les exigences difficiles à voir', 'Une information déterminante peut se trouver dans un règlement de consultation, un CPS, un bordereau ou une annexe.', [['Critères techniques', 'Repérez qualifications, normes, références ou moyens demandés.'], ['Pièces administratives', 'Identifiez attestations, déclarations et justificatifs mentionnés.'], ['Livrables et délais', 'Localisez les résultats attendus, phases et échéances.']]],
      ['Posez une question au dossier', 'Formulez une question simple et obtenez une réponse contextualisée lorsque les documents permettent de l’établir.', [['Question ciblée', '« Une visite des lieux est-elle obligatoire ? ».'], ['Réponse prudente', 'Le système distingue l’information trouvée, l’incertitude et l’absence de réponse.'], ['Référence', 'Le passage ou le document associé facilite le contrôle.']]],
      ['Une assistance, jamais une substitution', 'L’extraction automatique peut être incomplète ou erronée. Elle prépare la lecture mais ne remplace ni l’examen du dossier ni un avis professionnel.', [['Validation humaine', 'Faites relire les éléments qui engagent la candidature.'], ['Document officiel', 'Considérez toujours la pièce publiée comme référence.'], ['Signalement', 'Remontez une réponse imprécise pour améliorer le contrôle.']]],
    ],
  }),
  '/pertinence-opportunites-marches-publics': page({
    eyebrow: 'Profil d’entreprise',
    title: 'Classez les opportunités selon leur pertinence pour votre entreprise',
    seoTitle: 'Qualification des opportunités de marchés publics',
    text: 'Bido rapproche chaque opportunité de votre profil métier, de vos secteurs, régions, mots-clés, préférences et exclusions afin d’aider l’équipe à prioriser sa revue.',
    icon: Fingerprint,
    metrics: [['Profil métier', 'configurable'], ['Classement', 'expliqué'], ['Éligibilité', 'toujours vérifiée par vous']],
    features: [['Décrivez votre activité', 'Structurez les métiers, services, produits et territoires réellement couverts.'], ['Comprenez le classement', 'Identifiez les signaux favorables, absents ou défavorables.'], ['Décidez avec prudence', 'Utilisez la pertinence comme aide au tri, jamais comme garantie.']],
    sections: [
      ['Un profil qui reflète vos capacités', 'Le classement gagne en utilité lorsque le profil décrit précisément ce que votre entreprise souhaite et peut traiter.', [['Activités et secteurs', 'Renseignez vos familles de prestations et domaines prioritaires.'], ['Régions et exclusions', 'Définissez les zones servies et les cas à écarter.'], ['Préférences', 'Ajoutez des mots-clés, acheteurs ou caractéristiques à favoriser.']]],
      ['Une pertinence explicable', 'Un score isolé n’aide pas à décider. Bido présente les critères qui ont contribué au classement.', [['Signaux correspondants', 'Voyez les éléments alignés sur votre profil.'], ['Points à vérifier', 'Repérez les informations manquantes ou ambiguës.'], ['Motifs d’exclusion', 'Identifiez rapidement une contrainte incompatible.']]],
      ['La responsabilité reste humaine', 'La pertinence n’est ni un avis juridique, ni une validation administrative, ni une garantie de capacité ou de succès.', [['Vérification d’éligibilité', 'Contrôlez les conditions dans le règlement et les pièces officielles.'], ['Décision Go / No-Go', 'Faites valider l’arbitrage par les responsables concernés.'], ['Profil actualisé', 'Ajustez les critères lorsque la stratégie ou les capacités évoluent.']]],
    ],
  }),
  '/veille-marches-publics': page({
    eyebrow: 'Recherches sauvegardées',
    title: 'Transformez vos recherches en listes de veille marchés publics',
    seoTitle: 'Veille des marchés publics et appels d’offres',
    text: 'Enregistrez une recherche, organisez-la par secteur, région, client ou équipe, puis suivez les nouvelles opportunités sans reconstruire vos critères à chaque consultation.',
    icon: BellRing,
    metrics: [['Recherches', 'réutilisables'], ['Listes', 'organisées par objectif'], ['Nouveautés', 'faciles à identifier']],
    features: [['Sauvegardez le périmètre', 'Conservez les mots-clés, filtres et règles de classement.'], ['Organisez la veille', 'Créez des listes adaptées aux secteurs, zones ou équipes.'], ['Suivez les changements', 'Distinguez les opportunités récemment ajoutées ou proches de l’échéance.']],
    sections: [
      ['Une veille qui reste exploitable', 'Chaque recherche sauvegardée devient un point d’entrée stable vers un besoin commercial clairement défini.', [['Par secteur', 'Regroupez les opportunités BTP, IT, conseil, fournitures ou services.'], ['Par territoire', 'Suivez une région, une ville ou un périmètre d’intervention.'], ['Par équipe', 'Donnez à chaque responsable une liste correspondant à son domaine.']]],
      ['Moins de notifications, plus de contexte', 'Les alertes doivent signaler une action utile, pas reproduire tout le flux.', [['Fréquence configurable', 'Choisissez le rythme adapté au niveau de priorité.'], ['Résumé synthétique', 'Recevez les éléments nécessaires pour décider d’ouvrir le dossier.'], ['Échéance visible', 'Repérez les opportunités qui demandent une revue rapide.']]],
      ['Un rituel de revue partagé', 'La liste de veille facilite une revue régulière avec un statut, un responsable et une prochaine action.', [['À qualifier', 'Le dossier attend une première lecture.'], ['En analyse', 'Un responsable vérifie les conditions et documents.'], ['Décision prise', 'Le motif Go / No-Go est conservé.']]],
    ],
  }),
  '/detail-opportunite-marche-public': page({
    eyebrow: 'Dossier d’opportunité',
    title: 'Retrouvez toutes les informations d’un marché public dans une vue structurée',
    seoTitle: 'Détail et suivi d’une opportunité de marché public',
    text: 'Consultez la référence, l’acheteur, les dates, le budget, la caution, la procédure, les lots, les documents, le résumé et les points de vigilance avant de décider.',
    icon: Layers3,
    metrics: [['Contexte', 'regroupé'], ['Documents', 'accessibles depuis la vue'], ['Actions', 'partagées avec l’équipe']],
    features: [['Comprenez l’opportunité', 'Accédez aux informations structurées et à un résumé de première lecture.'], ['Préparez la vérification', 'Repérez les données manquantes, les dates et les points de vigilance.'], ['Organisez la suite', 'Sauvegardez, téléchargez, partagez, attribuez ou interrogez les documents.']],
    sections: [
      ['Une fiche conçue pour la qualification', 'La page rassemble les informations nécessaires à une première décision sans masquer la complexité du dossier.', [['Identification', 'Titre, référence, type AO ou BDC, acheteur et statut.'], ['Cadre financier et temporel', 'Budget disponible, caution, dates et délai lorsque publiés.'], ['Périmètre', 'Catégories, lots, région, ville et procédure.']]],
      ['Les documents restent la référence', 'Téléchargez les pièces disponibles et revenez à la publication officielle pour confirmer toute condition.', [['Inventaire des pièces', 'Identifiez le type de chaque document rattaché.'], ['Accès direct', 'Ouvrez ou téléchargez la pièce depuis l’opportunité.'], ['Vérification officielle', 'Contrôlez la version, la date et les éventuelles modifications.']]],
      ['Un dossier de travail partagé', 'La vue détaillée devient le point de coordination entre les personnes impliquées.', [['Notes internes', 'Conservez les observations sans modifier la source.'], ['Attribution', 'Désignez le responsable de l’analyse ou de la prochaine action.'], ['Historique', 'Retracez les statuts, décisions et changements importants.']]],
    ],
  }),
  '/analyseur-ia-marches-publics': page({
    eyebrow: 'Analyse assistée par IA',
    title: 'Analysez un marché public avec une IA reliée à son dossier',
    seoTitle: 'Analyseur IA de marchés publics au Maroc',
    text: 'Interrogez les documents d’un appel d’offres ou d’un bon de commande, obtenez une synthèse contextualisée et préparez une décision Go / No-Go fondée sur des éléments à vérifier.',
    icon: Sparkles,
    metrics: [['Questions', 'en langage naturel'], ['Réponses', 'contextualisées'], ['Sources', 'à vérifier dans le dossier']],
    features: [['Posez les bonnes questions', 'Interrogez les critères d’éligibilité, documents, dates, risques et prochaines étapes.'], ['Structurez l’analyse', 'Transformez les réponses en synthèse, checklist ou note de qualification.'], ['Gardez la maîtrise', 'Vérifiez les références et faites valider toute décision importante par votre équipe.']],
    sections: [
      ['Un analyseur IA pour préparer la lecture', 'Bido aide à parcourir un dossier plus efficacement en reliant les questions aux informations disponibles.', [['Éligibilité', '« Quels sont les critères d’éligibilité mentionnés ? ».'], ['Documents', '« Quelles pièces doivent être préparées ? ».'], ['Dates et risques', '« Quelles sont les échéances et les principaux points de vigilance ? ».']]],
      ['De la question à la note Go / No-Go', 'L’analyse peut être structurée selon vos critères internes afin de faciliter la revue par la direction, le commercial ou le bid manager.', [['Adéquation métier', 'Comparez l’objet et les exigences à votre profil d’entreprise.'], ['Capacité de réponse', 'Identifiez les moyens, références ou délais à confirmer.'], ['Prochaine action', 'Listez les vérifications et responsabilités avant la décision.']]],
      ['Une IA contrôlée et transparente', 'Une réponse générée peut être incomplète ou incorrecte. Bido présente l’IA comme une assistance à la qualification, jamais comme une décision automatique.', [['Références consultables', 'Ouvrez le document ou passage associé lorsque disponible.'], ['Incertitude signalée', 'Distinguez une information trouvée d’une interprétation à confirmer.'], ['Validation humaine', 'Les utilisateurs restent responsables de la lecture officielle et de la soumission.']]],
    ],
    faqs: [['Bido garantit-il l’éligibilité à un marché public ?', 'Non. L’analyse aide à repérer les critères et points de vigilance, mais l’entreprise doit vérifier son éligibilité dans les documents officiels.'], ['L’analyse fonctionne-t-elle sans document ?', 'La qualité dépend des informations et pièces disponibles. Bido doit signaler lorsque le contexte ne permet pas une réponse fiable.'], ['Peut-on générer une note Go / No-Go ?', 'Oui, comme document préparatoire fondé sur vos critères et soumis à validation humaine.']],
  }),
  '/agents-ia': page({
    eyebrow: 'Assistants configurables',
    title: 'Configurez des agents IA pour vos workflows d’appels d’offres',
    seoTitle: 'Agents et assistants IA pour appels d’offres',
    text: 'Créez des assistants spécialisés pour analyser, qualifier, vérifier, rédiger ou suivre une opportunité, avec des instructions, des sources, un format de sortie et une validation humaine.',
    icon: Bot,
    metrics: [['Rôles', 'préconfigurés ou personnalisés'], ['Contexte', 'délimité'], ['Sorties', 'validées avant utilisation']],
    features: [['Commencez avec un rôle clair', 'Utilisez un analyseur d’appel d’offres, un vérificateur de documents ou un assistant conformité.'], ['Adaptez les instructions', 'Définissez le contexte, les sources autorisées, les règles et le format attendu.'], ['Réutilisez en équipe', 'Partagez les agents approuvés dans votre espace de travail.']],
    sections: [
      ['Des agents pour les tâches répétitives', 'Chaque agent IA répond à une mission délimitée et produit un résultat que l’utilisateur doit relire.', [['Analyseur d’appel d’offres', 'Prépare une synthèse des informations et points à vérifier.'], ['Assistant de qualification', 'Applique une grille de lecture à une opportunité.'], ['Vérificateur de documents', 'Compare une liste attendue aux pièces identifiées.']]],
      ['Des assistants pour préparer la réponse', 'Les agents peuvent aider à organiser l’information ou produire une première version sans remplacer l’expertise métier.', [['Rédacteur de rapports', 'Structure une note de synthèse ou un compte rendu.'], ['Rédacteur d’e-mails', 'Prépare un message interne ou une demande de clarification.'], ['Assistant de délais', 'Rassemble les dates et propose un calendrier de contrôle.']]],
      ['Une configuration gouvernée', 'Un agent utile doit expliciter son objectif, ses limites et les sources qu’il peut exploiter.', [['Instructions partagées', 'Documentez le comportement et le résultat attendu.'], ['Format stable', 'Choisissez checklist, tableau, synthèse ou note.'], ['Validation obligatoire', 'Aucune sortie sensible ne doit être utilisée sans revue.']]],
    ],
  }),
  '/collaboration': page({
    eyebrow: 'Espace de travail',
    title: 'Coordonnez votre équipe autour de chaque opportunité publique',
    seoTitle: 'Collaboration et suivi des appels d’offres',
    text: 'Partagez les opportunités, attribuez les analyses, centralisez les notes et conservez l’historique des décisions dans un espace de travail commun.',
    icon: UsersRound,
    metrics: [['Membres', 'réunis dans un espace'], ['Rôles', 'adaptés aux responsabilités'], ['Historique', 'des décisions et actions']],
    features: [['Un dossier commun', 'Travaillez sur la même opportunité et les mêmes documents.'], ['Des responsabilités visibles', 'Attribuez un responsable, une échéance et une prochaine action.'], ['Une décision traçable', 'Conservez les notes, statuts et motifs Go / No-Go.']],
    sections: [
      ['Réduisez la dispersion de l’information', 'Les e-mails et messages isolés rendent la qualification difficile à suivre. Bido rattache les échanges utiles au dossier concerné.', [['Notes contextuelles', 'Ajoutez une observation sur l’opportunité ou une pièce.'], ['Mentions et attribution', 'Sollicitez la bonne personne et clarifiez la responsabilité.'], ['Statut partagé', 'Donnez à tous une lecture cohérente de l’avancement.']]],
      ['Adaptez la visibilité aux rôles', 'Organisez les membres et permissions selon la structure de votre entreprise.', [['Direction', 'Accède aux synthèses et décisions.'], ['Bid manager', 'Pilote l’analyse et la préparation.'], ['Expert métier', 'Contribue sur les exigences de son domaine.']]],
      ['Capitalisez sur les décisions', 'L’historique facilite les revues d’activité et évite de recommencer les mêmes analyses.', [['Motif Go / No-Go', 'Documentez les facteurs de décision.'], ['Chronologie', 'Retrouvez les changements de statut et actions.'], ['Connaissance interne', 'Conservez les enseignements utiles pour les prochaines opportunités.']]],
    ],
  }),
  '/alertes': page({
    eyebrow: 'Alertes et échéances',
    title: 'Suivez les nouveaux marchés publics et leurs échéances sans ajouter de bruit',
    seoTitle: 'Alertes et suivi des marchés publics',
    text: 'Recevez des alertes fondées sur vos recherches sauvegardées, suivez les dates importantes et configurez la fréquence selon la priorité de chaque liste de veille.',
    icon: BellRing,
    metrics: [['Nouveautés', 'selon vos recherches'], ['Rappels', 'avant les échéances'], ['Fréquence', 'configurable']],
    features: [['Surveillez vos critères', 'Déclenchez les alertes à partir d’une recherche sauvegardée.'], ['Priorisez les échéances', 'Visualisez les dates qui nécessitent une action.'], ['Partagez la vigilance', 'Rendez les alertes importantes visibles à l’équipe.']],
    sections: [
      ['Des alertes liées à une intention', 'Chaque notification doit correspondre à un périmètre compris par l’utilisateur.', [['Nouvelle opportunité', 'Signale un résultat ajouté à une liste de veille.'], ['Échéance proche', 'Rappelle une date importante selon le délai choisi.'], ['Changement à vérifier', 'Attire l’attention sur une information actualisée lorsqu’elle est disponible.']]],
      ['Un rythme adapté au besoin', 'Toutes les veilles n’ont pas la même urgence. Ajustez la fréquence sans perdre la visibilité.', [['Immédiat', 'Pour un périmètre critique et restreint.'], ['Résumé quotidien', 'Pour consolider les nouveautés utiles.'], ['Revue périodique', 'Pour les marchés exploratoires ou secondaires.']]],
      ['Une responsabilité partagée', 'Associez la notification à une personne ou une équipe et transformez-la en action.', [['Propriétaire', 'Identifiez qui doit examiner l’opportunité.'], ['Priorité', 'Distinguez l’urgent de l’important.'], ['Suivi', 'Conservez le statut après la notification.']]],
    ],
  }),
  '/documents-marches-publics': page({
    eyebrow: 'Documents et téléchargements',
    title: 'Organisez les documents de vos marchés publics sans perdre leur origine',
    seoTitle: 'Documents et pièces des marchés publics',
    text: 'Regroupez les pièces disponibles depuis l’opportunité, identifiez leur type, téléchargez-les et utilisez l’analyse assistée par IA tout en conservant la vérification de la source officielle.',
    icon: FileCheck2,
    metrics: [['Pièces', 'regroupées par opportunité'], ['Types', 'identifiés pour la lecture'], ['Source', 'conservée pour vérification']],
    features: [['Un inventaire lisible', 'Visualisez les pièces disponibles et leur rattachement au dossier.'], ['Un accès contextualisé', 'Ouvrez le document depuis l’opportunité, l’analyse ou une réponse IA.'], ['Une utilisation prudente', 'Vérifiez la version et la publication officielle avant toute action.']],
    sections: [
      ['Rassemblez les pièces du dossier', 'Bido facilite la consultation des documents accessibles sans prétendre remplacer l’archive officielle de l’acheteur.', [['Classification', 'Distinguez avis, règlement, CPS, bordereau et annexes lorsque l’information le permet.'], ['Téléchargement', 'Récupérez une pièce pour votre travail interne.'], ['Lien d’origine', 'Conservez le contexte de publication.']]],
      ['Travaillez à partir du document', 'Les pièces peuvent alimenter la recherche, le chat IA, les checklists et les synthèses.', [['Recherche ciblée', 'Trouvez une notion dans le texte exploitable.'], ['Questions contextualisées', 'Interrogez une pièce ou l’ensemble du dossier.'], ['Notes internes', 'Ajoutez une observation sans altérer le document.']]],
      ['Protégez les documents internes', 'Les documents ajoutés par l’entreprise doivent respecter les règles d’accès et de conservation de l’espace de travail.', [['Accès contrôlé', 'Limitez la visibilité selon les rôles.'], ['Suppression maîtrisée', 'Définissez les règles de retrait et de conservation.'], ['Données sensibles', 'Évitez d’importer une information non nécessaire au traitement.']]],
    ],
  }),
  '/reporting': page({
    eyebrow: 'Rapports et exports',
    title: 'Transformez votre pipeline de marchés publics en rapports exploitables',
    seoTitle: 'Reporting et suivi des appels d’offres',
    text: 'Préparez des listes d’opportunités, notes Go / No-Go, synthèses de direction et rapports d’équipe à partir des informations validées dans votre espace de travail.',
    icon: ChartNoAxesCombined,
    metrics: [['Pipeline', 'consolidé'], ['Rapports', 'orientés décision'], ['Exports', 'pour les outils internes']],
    features: [['Donnez de la visibilité', 'Présentez les volumes, statuts, échéances et priorités.'], ['Standardisez les synthèses', 'Utilisez une structure cohérente pour comparer les dossiers.'], ['Partagez les données utiles', 'Exportez les listes autorisées vers vos traitements internes.']],
    sections: [
      ['Des rapports adaptés aux décideurs', 'La direction a besoin d’une lecture synthétique, tandis que l’équipe opérationnelle doit accéder au détail.', [['Synthèse de direction', 'Présente les opportunités prioritaires, risques et prochaines décisions.'], ['Revue d’équipe', 'Suit les responsables, actions et échéances.'], ['Note Go / No-Go', 'Formalise les critères, réserves et validation.']]],
      ['Des exports maîtrisés', 'Transférez les informations nécessaires sans multiplier les copies non contrôlées.', [['Liste structurée', 'Exportez les champs utiles à une analyse complémentaire.'], ['Périmètre choisi', 'Limitez l’export à une recherche ou une liste de veille.'], ['Traçabilité', 'Documentez l’origine et la date des données exportées.']]],
      ['Des documents préparés par les agents', 'Un agent IA peut produire une première structure de rapport, toujours relue avant diffusion.', [['Format approuvé', 'Utilisez un modèle défini par l’organisation.'], ['Sources indiquées', 'Rattachez les constats importants au dossier.'], ['Validation', 'Conservez l’auteur de la revue finale.']]],
    ],
  }),
  '/integrations': page({
    eyebrow: 'Intégrations',
    title: 'Connectez votre veille marchés publics à vos outils de travail',
    seoTitle: 'Intégrations pour logiciel d’appels d’offres',
    text: 'Reliez progressivement Bido à la messagerie, au calendrier, au stockage cloud, aux tableurs, au CRM ou à vos systèmes internes selon les connecteurs disponibles.',
    icon: Workflow,
    metrics: [['Messagerie', 'pour les alertes'], ['Calendrier', 'pour les échéances'], ['API', 'selon l’offre et le besoin']],
    features: [['Informez au bon endroit', 'Faites circuler les alertes et synthèses dans les canaux prévus.'], ['Synchronisez les échéances', 'Ajoutez les dates importantes au calendrier de l’équipe.'], ['Étendez avec contrôle', 'Étudiez les API et webhooks selon les règles de sécurité.']],
    sections: [
      ['Des statuts d’intégration transparents', 'Chaque connecteur doit indiquer clairement son niveau de disponibilité avant toute promesse commerciale.', [['Disponible', 'Fonction testée et ouverte selon l’offre.'], ['Bêta', 'Fonction accessible avec un périmètre et des limites documentés.'], ['Prochainement ou sur demande', 'Intégration planifiée ou étudiée selon le contexte.']]],
      ['Les outils du quotidien', 'Les premières intégrations doivent réduire les ressaisies les plus fréquentes.', [['E-mail et messagerie', 'Recevez un résumé ou partagez une opportunité.'], ['Calendrier', 'Suivez une date limite ou un jalon interne.'], ['Tableur et stockage', 'Exportez une liste ou organisez les fichiers autorisés.']]],
      ['Les environnements avancés', 'Les organisations peuvent étudier une connexion à leur CRM, ERP ou système documentaire.', [['API', 'Accès programmatique encadré par l’offre et les permissions.'], ['Webhooks', 'Notification d’un événement défini.'], ['Sécurité', 'Authentification, journalisation et limitation des accès.']]],
    ],
  }),
  '/securite': page({
    eyebrow: 'Sécurité et confiance',
    title: 'Protégez vos espaces, documents et analyses de marchés publics',
    seoTitle: 'Sécurité du logiciel de marchés publics Bido',
    text: 'Bido adopte une approche de sécurité par conception fondée sur le contrôle des accès, la protection des comptes, l’isolation des espaces et une utilisation responsable de l’intelligence artificielle.',
    icon: ShieldCheck,
    metrics: [['Accès', 'selon les rôles'], ['Espaces', 'isolés logiquement'], ['IA', 'soumise à validation humaine']],
    features: [['Contrôlez les accès', 'Adaptez les permissions aux responsabilités et retirez les accès devenus inutiles.'], ['Protégez les données', 'Encadrez les sessions, téléchargements, sauvegardes et suppressions.'], ['Utilisez l’IA avec prudence', 'Gardez les sources, limites et validations visibles.']],
    sections: [
      ['Sécurité des comptes et espaces', 'Les mesures finales seront documentées selon l’architecture réellement déployée, sans revendiquer de certification non obtenue.', [['Protection des comptes', 'Authentification, gestion des sessions et récupération encadrée.'], ['Contrôle par rôle', 'Permissions adaptées aux membres et administrateurs.'], ['Isolation', 'Séparation logique des espaces de travail.']]],
      ['Cycle de vie des données', 'L’entreprise doit comprendre où se trouvent ses informations, combien de temps elles sont conservées et comment les récupérer ou les supprimer.', [['Export', 'Modalités de récupération définies par l’offre.'], ['Conservation', 'Durées documentées selon la catégorie de donnée.'], ['Suppression', 'Processus contrôlé avec les limites légales ou techniques applicables.']]],
      ['IA responsable', 'Les fonctions d’analyse sont conçues pour assister la lecture et non pour produire une décision incontestable.', [['Transparence', 'Distinguez source, extraction et génération.'], ['Supervision', 'Faites vérifier les résultats importants.'], ['Signalement', 'Permettez aux utilisateurs de remonter une réponse problématique.']]],
    ],
  }),
  '/guides-marches-publics': page({
    eyebrow: 'Guides pratiques',
    title: 'Des guides pour structurer votre réponse aux marchés publics',
    seoTitle: 'Guides pratiques des marchés publics au Maroc',
    text: 'Accédez à des méthodes prêtes à adapter pour la veille, la qualification Go / No-Go, la vérification documentaire, les échéances, l’IA contrôlée et le workflow d’équipe.',
    icon: ScrollText,
    features: [['Veille et recherche', 'Construire un périmètre utile et une routine de revue.'], ['Qualification', 'Formaliser les critères avant de mobiliser l’équipe.'], ['Préparation', 'Organiser documents, responsabilités et échéances.']],
    sections: [
      ['Six guides pour commencer', 'Ces contenus pédagogiques doivent aider les équipes à améliorer leur méthode, indépendamment de l’outil.', [['Structurer une veille marchés publics', 'Définir les secteurs, territoires, mots-clés et exclusions.'], ['Construire une grille Go / No-Go', 'Comparer intérêt commercial, capacité, risque et délai.'], ['Vérifier un dossier', 'Organiser la lecture des exigences et pièces attendues.']]],
      ['Des workflows applicables', 'Chaque guide propose une séquence, des questions de contrôle et un livrable simple.', [['Maîtriser les échéances', 'Créer un calendrier de contrôles internes.'], ['Utiliser l’IA avec contrôle', 'Définir les usages, sources et validations.'], ['Coordonner l’équipe', 'Attribuer les rôles et conserver les décisions.']]],
    ],
  }),
  '/cas-usage': page({
    eyebrow: 'Scénarios illustratifs',
    title: 'Voyez comment Bido s’intègre dans différents workflows de marchés publics',
    seoTitle: 'Cas d’usage du logiciel de marchés publics Bido',
    text: 'Découvrez trois scénarios fictifs et réalistes pour comprendre l’usage de Bido dans une entreprise BTP, une société informatique et un cabinet de conseil.',
    icon: BriefcaseBusiness,
    features: [['BTP', 'Surveiller les travaux adaptés aux qualifications et zones d’intervention.'], ['IT', 'Identifier les prestations numériques et vérifier les exigences techniques.'], ['Conseil', 'Organiser plusieurs veilles et produire des synthèses homogènes.']],
    sections: [
      ['Entreprise BTP', 'L’équipe commerciale surveille les travaux par région et catégorie, puis transmet les dossiers prioritaires au bureau d’études.', [['Détection', 'Une liste de veille cible les travaux correspondant aux métiers.'], ['Qualification', 'Le responsable contrôle qualification, caution, délai et moyens.'], ['Décision', 'La direction valide une note Go / No-Go documentée.']]],
      ['Société informatique', 'Le business developer recherche les marchés de maintenance, logiciels et infrastructure, y compris dans le contenu des pièces.', [['Recherche naturelle', 'La requête combine prestation, ville et durée.'], ['Analyse technique', 'L’expert repère les technologies et niveaux de service.'], ['Planification', 'Les dates et documents sont attribués à l’équipe.']]],
      ['Cabinet de conseil', 'Le cabinet organise plusieurs veilles clients tout en conservant un cadre de lecture commun.', [['Listes séparées', 'Chaque mission dispose de son périmètre.'], ['Agent analyste', 'Une structure de synthèse est réutilisée.'], ['Validation consultant', 'L’expert vérifie et adapte le livrable.']]],
    ],
  }),
  '/carrieres': page({
    eyebrow: 'Carrières',
    title: 'Construisez des outils utiles aux entreprises qui répondent aux marchés publics',
    seoTitle: 'Carrières chez Bido.ma',
    text: 'Bido développe une plateforme marocaine exigeante, sobre et responsable. Les recrutements seront publiés ici lorsqu’un besoin réel sera ouvert.',
    icon: Building2,
    features: [['Mission claire', 'Rendre l’information publique plus exploitable pour les entreprises.'], ['Travail responsable', 'Privilégier la précision, la sécurité et la valeur utilisateur.'], ['Candidatures honnêtes', 'Aucun poste fictif ni promesse de recrutement.']],
    sections: [
      ['Notre manière de travailler', 'Nous cherchons un équilibre entre ambition produit, discipline d’exécution et compréhension du contexte marocain.', [['Problèmes réels', 'Commencer par le besoin utilisateur et le workflow.'], ['Qualité observable', 'Tester les fonctionnalités, contenus et limites.'], ['Décisions documentées', 'Expliquer les choix importants et leurs compromis.']]],
      ['Processus de recrutement', 'Lorsqu’un poste sera ouvert, le processus et les attentes seront présentés clairement.', [['Échange de cadrage', 'Comprendre l’expérience et les motivations.'], ['Exercice adapté', 'Évaluer une compétence pertinente sans travail gratuit excessif.'], ['Décision et retour', 'Communiquer les étapes et le résultat.']]],
    ],
  }),
  '/centre-aide': page({
    eyebrow: 'Centre d’aide',
    title: 'Trouvez une réponse sur la recherche, l’analyse et le suivi dans Bido',
    seoTitle: 'Centre d’aide Bido',
    text: 'Consultez les guides de prise en main, les explications sur les opportunités et documents, ainsi que les bonnes pratiques d’utilisation de l’IA.',
    icon: CheckCheck,
    features: [['Premiers pas', 'Configurer le profil d’entreprise et l’espace de travail.'], ['Recherche et veille', 'Créer des requêtes, filtres et listes sauvegardées.'], ['IA et documents', 'Interroger un dossier et vérifier les réponses.']],
    sections: [
      ['Articles populaires', 'Le centre d’aide doit répondre rapidement aux actions principales du produit.', [['Configurer mon profil métier', 'Décrire activités, secteurs, régions et exclusions.'], ['Créer une recherche sauvegardée', 'Transformer des filtres en liste de veille.'], ['Comprendre la pertinence', 'Lire les signaux sans confondre score et éligibilité.']]],
      ['Obtenir de l’aide', 'Si la documentation ne suffit pas, contactez le support avec le contexte utile sans transmettre d’information sensible inutile.', [['Question produit', 'Décrivez l’action et le résultat attendu.'], ['Problème de donnée', 'Indiquez la référence et la source concernées.'], ['Problème technique', 'Précisez la page, l’heure et les étapes observées.']]],
    ],
  }),
  '/statut': page({
    eyebrow: 'État du service',
    title: 'Consultez la disponibilité des services Bido',
    seoTitle: 'Statut du service Bido',
    text: 'Cette page communiquera les incidents, maintenances et performances dégradées de manière factuelle, avec les composants concernés et l’historique disponible.',
    icon: LockKeyhole,
    features: [['Systèmes opérationnels', 'Aucun incident connu sur les composants suivis.'], ['Incident en cours', 'Description factuelle, impact et prochaine mise à jour.'], ['Maintenance planifiée', 'Période, services concernés et impact attendu.']],
    sections: [
      ['Des messages compréhensibles', 'Le statut doit informer sans minimiser l’impact ni annoncer un délai non maîtrisé.', [['Performance dégradée', 'Certaines actions peuvent être plus lentes ou indisponibles.'], ['Incident résolu', 'Le service est rétabli et le suivi est clôturé.'], ['Historique', 'Consultez les événements précédents et leurs mises à jour.']]],
      ['Notifications de statut', 'Les utilisateurs pourront s’abonner aux mises à jour lorsqu’un canal fiable sera configuré.', [['Abonnement', 'Choisissez les notifications disponibles.'], ['Mise à jour', 'Recevez uniquement les changements importants.'], ['Désabonnement', 'Retirez le canal à tout moment.']]],
    ],
  }),
};
