'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import {
  ArrowRight, BellRing, Bot, Building2, Check, CheckCircle2, ChevronDown, Clock3,
  Cookie, FileCheck2, FileSearch, Globe2, LayoutDashboard, Menu, MessageSquareText,
  Search, Send, ShieldCheck, Sparkles, Target, UsersRound, Workflow, X,
} from 'lucide-react';
import { localizedContent, localizedHref } from './localized-content';
import { company } from './config';
import { BlogArticle, BlogIndex } from './BlogPages';
import ProductShowcase from './ProductShowcase';

const productNav = [
  ['/plateforme', 'platform'], ['/opportunites', 'opportunities'], ['/analyse-appels-offres', 'tenderAnalysis'],
  ['/analyse-documents', 'documents'], ['/agents-ia', 'agents'], ['/collaboration', 'collaboration'],
  ['/alertes', 'alerts'], ['/reporting', 'reporting'], ['/integrations', 'integrations'], ['/securite', 'security'],
];
const solutionPaths = ['/solutions/pme','/solutions/entreprises','/solutions/bid-managers','/solutions/developpement-commercial','/solutions/consultants','/secteurs/btp','/secteurs/it','/secteurs/services','/secteurs/fournitures'];

function Logo({ locale, light = false }) {
  return <Link href={localizedHref(locale, '/')} className={`logo ${light ? 'logo-light' : ''}`} aria-label="Bido"><img className="brand-logo" src="/logo.png" alt="Bido.ma" width="720" height="210" /></Link>;
}

function Header({ locale, pathname }) {
  const c = localizedContent[locale].common;
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [dropdown, setDropdown] = useState(null);
  const changeLocale = (next) => router.push(localizedHref(next, pathname));
  return <>
    <header className="site-header">
      <div className="nav-wrap">
        <Logo locale={locale}/>
        <nav className="desktop-nav" aria-label={c.menu}>
          <div className="nav-dropdown" onMouseEnter={()=>setDropdown('product')} onMouseLeave={()=>setDropdown(null)}>
            <button aria-expanded={dropdown==='product'}>{c.product}<ChevronDown size={14}/></button>
            {dropdown==='product'&&<div className="dropdown-panel">{productNav.map(([path,key])=><Link key={path} href={localizedHref(locale,path)}><span>{c[key]}</span><ArrowRight size={14}/></Link>)}</div>}
          </div>
          <div className="nav-dropdown" onMouseEnter={()=>setDropdown('solutions')} onMouseLeave={()=>setDropdown(null)}>
            <button aria-expanded={dropdown==='solutions'}>{c.solutions}<ChevronDown size={14}/></button>
            {dropdown==='solutions'&&<div className="dropdown-panel">{solutionPaths.slice(0,5).map(path=><Link key={path} href={localizedHref(locale,path)}><span>{localizedContent[locale].solutions[path][0]}</span><ArrowRight size={14}/></Link>)}</div>}
          </div>
          <Link href={localizedHref(locale,'/tarifs')}>{c.pricing}</Link>
          <Link href={localizedHref(locale,'/blog')}>Blog</Link>
          <Link href={localizedHref(locale,'/a-propos')}>{c.company}</Link>
        </nav>
        <div className="header-actions">
          <label className="locale-select"><Globe2 size={16}/><span className="sr-only">{c.language}</span><select value={locale} onChange={e=>changeLocale(e.target.value)}><option value="fr">FR</option><option value="en">EN</option><option value="ar">AR</option></select></label>
          <a href={company.loginUrl} className="text-link">{c.login}</a>
          <Link href={company.appUrl} className="button small">{c.demo}<ArrowRight size={15}/></Link>
          <button className="menu-button" onClick={()=>setOpen(true)} aria-label={c.menu}><Menu/></button>
        </div>
      </div>
    </header>
    {open&&<div className="mobile-panel" role="dialog" aria-modal="true"><div className="mobile-top"><Logo locale={locale}/><button onClick={()=>setOpen(false)} aria-label={c.close}><X/></button></div><nav><div><strong>{c.product}</strong>{productNav.slice(0,6).map(([path,key])=><Link key={path} href={localizedHref(locale,path)}>{c[key]}</Link>)}</div><div><strong>{c.solutions}</strong>{solutionPaths.slice(0,5).map(path=><Link key={path} href={localizedHref(locale,path)}>{localizedContent[locale].solutions[path][0]}</Link>)}</div><div><strong>{c.company}</strong><Link href={localizedHref(locale,'/a-propos')}>{c.about}</Link><Link href={localizedHref(locale,'/ressources')}>{c.resources}</Link><Link href={localizedHref(locale,'/contact')}>{c.contact}</Link></div></nav><Link href={company.appUrl} className="button">{c.demo}<ArrowRight size={16}/></Link></div>}
  </>;
}

function LocalizedMockup({ locale }) {
  const ar = locale === 'ar';
  return <div className="mock-shell" aria-hidden="true"><div className="mock-top"><div className="mock-brand"><span/><b>Bido</b></div><div className="mock-search"><Search size={13}/>{ar?'البحث عن فرصة…':'Search opportunities…'}</div><div className="avatar">HB</div></div><div className="mock-body"><aside><LayoutDashboard size={16}/><Search size={16}/><FileCheck2 size={16}/><Bot size={16}/><UsersRound size={16}/></aside><main><div className="mock-heading"><div><small>{ar?'محفظتكم':'YOUR PIPELINE'}</small><h3>{ar?'الفرص المقترحة':'Recommended opportunities'}</h3></div><button>{ar?'رصد جديد +':'+ New monitor'}</button></div><div className="mini-stats"><div><span>{ar?'للتأهيل':'To qualify'}</span><strong>24</strong><small>+6</small></div><div><span>{ar?'قيد التحليل':'In analysis'}</span><strong>08</strong><small>3</small></div><div><span>{ar?'للإيداع':'To submit'}</span><strong>05</strong><small>{ar?'هذا الشهر':'This month'}</small></div></div><div className="opportunity-table">{[['Urban development works','92%'],['Technical study & supervision','87%'],['IT equipment','76%']].map(([name,score],i)=><div className="table-row" key={name}><div><i className={`file-icon c${i}`}><FileSearch size={15}/></i><span><b>{ar?['أشغال التهيئة الحضرية','دراسة تقنية وتتبع','تجهيزات معلوماتية'][i]:name}</b><small>{ar?'المغرب · فرصة عمومية':'Morocco · Public opportunity'}</small></span></div><span className="score">{score}</span><span>{12+i*3}{ar?' يوم':'d'}</span></div>)}</div></main></div><div className="analysis-float"><div><Sparkles size={14}/><b>{ar?'تحليل Bido':'Bido analysis'}</b><span>{ar?'جاهز':'Ready'}</span></div><p>{ar?'ملاءمة قوية مع ملف مقاولتكم.':'Strong match with your company profile.'}</p><div className="progress"><i/></div></div></div>;
}

function Home({ locale }) {
  const h = localizedContent[locale].home;
  const icons = [Clock3, FileSearch, MessageSquareText];
  const stepIcons = [Search, Target, Sparkles, UsersRound];
  return <main id="main">
    <section className="hero"><div className="blueprint"/><div className="container"><div className="notice"><span>{h.noticeBadge}</span><p>{h.notice}</p><Link href={company.appUrl}>{h.noticeCta}<ArrowRight size={14}/></Link></div><div className="hero-grid"><div className="hero-copy"><div className="eyebrow"><span/><b>{h.eyebrow}</b></div><h1>{h.hero}</h1><p>{h.sub}</p><div className="hero-actions"><Link className="button" href={company.appUrl}>{h.primary}<ArrowRight size={17}/></Link><a className="button ghost" href="#workflow">{h.secondary}</a></div><div className="hero-proof"><div className="faces"><span>AM</span><span>SA</span><span>YK</span></div><p><b>{h.proof}</b></p></div></div><LocalizedMockup locale={locale}/></div></div></section>
    <section className="trust-strip"><div className="container"><span>{h.trusted}</span><div><b><Building2/>{locale==='ar'?'البناء والهندسة':'CONSTRUCTION'}</b><b><Workflow/>{locale==='ar'?'الخدمات':'SERVICES'}</b><b><Target/>{locale==='ar'?'الاستشارة':'CONSULTING'}</b><b><Sparkles/>{locale==='ar'?'التكنولوجيا':'TECHNOLOGY'}</b></div></div></section>
    <section className="section problem"><div className="container narrow"><div className="section-label">{h.problemLabel}</div><h2>{h.problemTitle}</h2><p className="lead">{h.problemLead}</p><div className="problem-grid">{h.problems.map(([title,text],i)=>{const Icon=icons[i];return <article key={title}><span>0{i+1}</span><Icon/><h3>{title}</h3><p>{text}</p></article>})}</div></div></section>
    <section className="section platform-section" id="workflow"><div className="container"><div className="split-heading"><div><div className="section-label light">{h.platformLabel}</div><h2>{h.platformTitle}</h2></div><p>{h.platformText}</p></div><div className="platform-grid">{h.steps.map(([title,text],i)=>{const Icon=stepIcons[i];return <article key={title}><div className="num">0{i+1}</div><Icon/><h3>{title}</h3><p>{text}</p><Link href={localizedHref(locale,'/plateforme')}>{localizedContent[locale].common.explore}<ArrowRight size={15}/></Link></article>})}</div></div></section>
    <section className="section workflow"><div className="container"><div className="feature-layout"><div className="feature-copy"><div className="section-label">{h.discoveryLabel}</div><h2>{h.discoveryTitle}</h2><p>{h.discoveryText}</p><ul>{h.discoveryPoints.map(x=><li key={x}><CheckCircle2/>{x}</li>)}</ul><Link href={localizedHref(locale,'/opportunites')} className="inline-cta">{h.discoveryCta}<ArrowRight/></Link></div><div className="opportunity-panel"><div className="panel-toolbar"><span><Search size={15}/>{locale==='ar'?'أشغال، دراسات، خدمات':'Works, studies, services'}</span><button>{locale==='ar'?'مرشحات':'Filters'} <b>4</b></button></div>{[92,84].map((score,i)=><div className={`op-card ${i===0?'selected':''}`} key={score}><div className="op-card-top"><span className="op-type">{locale==='ar'?'فرصة عمومية':'PUBLIC OPPORTUNITY'}</span><span className="match">{score}%</span></div><h4>{locale==='ar'?['أشغال التهيئة والتأهيل الحضري','دراسات تقنية وتتبع الأشغال'][i]:['Urban development and upgrading works','Technical studies and works supervision'][i]}</h4><p>{locale==='ar'?'المغرب · أجل محدد':'Morocco · Defined deadline'}</p></div>)}</div></div></div></section>
    <section className="section ai-section"><div className="container"><div className="ai-grid"><div className="analysis-panel"><div className="doc-side"><div className="doc-header"><FileCheck2/><span><b>{locale==='ar'?'وثيقة الصفقة.pdf':'Tender document.pdf'}</b><small>{locale==='ar'?'64 صفحة':'64 pages'}</small></span></div><div className="doc-lines"><b/><i/><i/><i/><b/><i/><i/><i/><i/></div></div><div className="ai-side"><div className="ai-head"><span><Sparkles/>{locale==='ar'?'الخلاصة التنفيذية':'Executive summary'}</span><b>AI</b></div><div className="risk-box"><i>{locale==='ar'?'نقطة انتباه':'ATTENTION POINT'}</i><p>{locale==='ar'?'الزيارة الميدانية إلزامية قبل الإيداع.':'The site visit is mandatory before submission.'}</p></div>{(locale==='ar'?[['الموضوع','خدمات تقنية'],['الأجل','8 أشهر'],['الضمان','28,000 درهم']]:[['Scope','Technical services'],['Deadline','8 months'],['Guarantee','28,000 MAD']]).map(([a,b])=><div className="analysis-row" key={a}><span>{a}</span><b>{b}</b></div>)}</div></div><div className="feature-copy"><div className="section-label light">{h.documentLabel}</div><h2>{h.documentTitle}</h2><p>{h.documentText}</p><div className="quote-line"><ShieldCheck/><p><b>{h.aiRule}</b><br/>{h.aiRuleText}</p></div><Link href={localizedHref(locale,'/analyse-documents')} className="inline-cta light-link">{h.documentCta}<ArrowRight/></Link></div></div></div></section>
    <section className="section outcomes"><div className="container"><div className="center-heading"><div className="section-label">{h.impactLabel}</div><h2>{h.impactTitle}</h2></div><div className="outcome-grid">{h.outcomes.map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <LocalizedFAQ locale={locale} preview/>
    <FinalCTA locale={locale}/>
  </main>;
}

function PageIntro({ label, title, text }) { return <section className="simple-hero"><div className="blueprint"/><div className="container"><div className="eyebrow"><span/><b>{label}</b></div><h1>{title}</h1><p>{text}</p></div></section>; }

function StandardPage({ locale, data, solution = false, path }) {
  const c=localizedContent[locale].common; const [label,title,text,features]=data;
  const items=features||[[locale==='ar'?'رصد ملائم':'Adapted monitoring',locale==='ar'?'اضبط Bido وفق أولويات فريقكم.':'Configure Bido around your team priorities.'],[locale==='ar'?'تحليل منسجم':'Consistent analysis',locale==='ar'?'طبّق شبكة قراءة موحدة مع الحفاظ على الحكم المهني.':'Apply one evaluation framework while retaining professional judgment.'],[locale==='ar'?'قيادة واضحة':'Clear management',locale==='ar'?'شارك التقدم والآجال والقرارات.':'Share progress, deadlines and decisions.']];
  return <main id="main"><section className="page-hero"><div className="blueprint"/><div className="container"><div className="page-hero-grid"><div><div className="eyebrow"><span/><b>{label}</b></div><h1>{title}</h1><p>{text}</p><div className="hero-actions"><Link className="button" href={company.appUrl}>{c.requestDemo}<ArrowRight/></Link><Link className="button ghost" href={localizedHref(locale,'/tarifs')}>{c.seePricing}</Link></div></div><div className="page-icon-card">{solution?<UsersRound/>:<Sparkles/>}<div className="rings"/><span>BIDO / {label}</span></div></div></div></section><ProductShowcase path={path} locale={locale}/><section className="section"><div className="container"><div className="center-heading"><div className="section-label">{c.capabilities}</div><h2>{locale==='ar'?'مصممة لتندمج في عملياتكم الفعلية.':'Designed for real operational workflows.'}</h2></div><div className="detail-cards">{items.map(([t,p],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{p}</p><ArrowRight/></article>)}</div></div></section><section className="workflow-band"><div className="container"><p>{c.workflow}</p><div>{[[c.detect],[c.qualify],[c.analyze],[c.decide]].map(([x],i)=><span key={x}><b>0{i+1}</b>{x}{i<3&&<ArrowRight/>}</span>)}</div></div></section><FinalCTA locale={locale}/></main>;
}

function Pricing({ locale }) { const p=localizedContent[locale].pricing; return <main id="main"><PageIntro label={p.label} title={p.title} text={p.text}/><section className="section pricing-page"><div className="container"><div className="plan-grid four">{p.plans.map(([name,desc,items],i)=><article className={i===1?'featured':''} key={name}>{i===1&&<span className="popular">{locale==='ar'?'الأكثر اختياراً':'MOST CHOSEN'}</span>}<h3>{name}</h3><p>{desc}</p><div className="price">{p.demand}</div><small>{p.note}</small><ul>{items.map(x=><li key={x}><Check/>{x}</li>)}</ul><Link href={company.appUrl} className={`button ${i===1?'':'outline'}`}>{p.cta}<ArrowRight/></Link></article>)}</div><div className="pricing-note"><ShieldCheck/><p><b>{p.transparency}</b> {p.transparencyText}</p></div></div></section><LocalizedFAQ locale={locale}/></main>; }

function About({ locale }) { const a=localizedContent[locale].about; return <main id="main"><PageIntro label={a.label} title={a.title} text={a.text}/><section className="section"><div className="container about-grid"><div><div className="section-label">{a.vision}</div><h2>{a.visionTitle}</h2></div><div>{a.paragraphs.map(x=><p key={x}>{x}</p>)}</div></div><div className="container values-grid">{a.values.map(([t,p],i)=><article key={t}><b>0{i+1}</b><h3>{t}</h3><p>{p}</p></article>)}</div></section><FinalCTA locale={locale}/></main>; }

function Contact({ locale, demo=false }) { const t=localizedContent[locale].contact; const [sent,setSent]=useState(false); const sectors=locale==='ar'?['البناء والهندسة','الخدمات','التكنولوجيا']:['Construction','Services','Technology']; return <main id="main"><section className="contact-section"><div className="container contact-grid"><div><div className="eyebrow"><span/><b>{demo?t.demoLabel:t.contactLabel}</b></div><h1>{demo?t.demoTitle:t.contactTitle}</h1><p>{demo?t.demoText:t.contactText}</p><div className="contact-points"><div><MessageSquareText/><span><b>{locale==='ar'?'تبادل مركز':'Focused exchange'}</b>{locale==='ar'?'محادثة مرتبطة بمساركم الفعلي.':'A conversation focused on your actual workflow.'}</span></div><div><ShieldCheck/><span><b>{locale==='ar'?'الخصوصية':'Privacy'}</b>{locale==='ar'?'لا تشاركوا وثائق حساسة.':'Do not share sensitive documents here.'}</span></div></div></div>{sent?<div className="form-success"><CheckCircle2/><h3>{t.success}</h3><p>{t.successText}</p></div>:<form className="contact-form" onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="form-row"><label>{t.name}<input required/></label><label>{t.email}<input required type="email"/></label></div><div className="form-row"><label>{t.business}<input required/></label><label>{t.role}<input/></label></div>{demo&&<div className="form-row"><label>{t.team}<select><option>1–5</option><option>6–20</option><option>21+</option></select></label><label>{t.sector}<select>{sectors.map(x=><option key={x}>{x}</option>)}</select></label></div>}<label>{t.need}<textarea required rows="5" placeholder={demo?t.demoMessage:t.message}/></label><label className="checkbox"><input required type="checkbox"/><span>{t.consent}</span></label><button className="button" type="submit">{demo?t.request:t.send}<Send size={16}/></button><small>{t.localNotice}</small></form>}</div></section></main>; }

function Resources({ locale }) { const r=localizedContent[locale].resources; return <main id="main"><PageIntro label={r.label} title={r.title} text={r.text}/><section className="section"><div className="container resource-grid">{r.cards.map(([type,title,text],i)=><article key={title}><div className={`resource-visual v${i}`}><FileSearch/><span>{type}</span></div><small>{type}</small><h3>{title}</h3><p>{text}</p><Link href={localizedHref(locale,'/ressources/veille-structuree')}>{localizedContent[locale].common.readMore}<ArrowRight/></Link></article>)}</div></section><FinalCTA locale={locale}/></main>; }

function Article({ locale }) { const r=localizedContent[locale].resources; return <main id="main"><article className="article-page"><header><div className="section-label">{r.cards[0][0]}</div><h1>{r.cards[0][1]}</h1><p>{r.cards[0][2]}</p><div className="byline"><span>BI</span><p><b>{locale==='ar'?'فريق Bido':'Bido team'}</b><br/>{locale==='ar'?'تم التحديث في يوليوز 2026':'Updated July 2026'}</p></div></header><div className="article-body"><aside><b>{locale==='ar'?'في هذا الدليل':'IN THIS GUIDE'}</b><a href="#profile">1. {locale==='ar'?'تحديد الملف':'Define the profile'}</a><a href="#signals">2. {locale==='ar'?'اختيار الإشارات':'Choose signals'}</a></aside><div><p className="intro">{locale==='ar'?'الرصد الفعال ليس الذي يجمع أكبر عدد من الإعلانات، بل الذي يساعد الفريق على اكتشاف الملفات المتوافقة مع استراتيجيته وقدراته.':'Effective monitoring is not about collecting the most notices. It helps the team identify opportunities aligned with strategy and capacity.'}</p><h2 id="profile">1. {locale==='ar'?'حدد ملف الفرصة بوضوح':'Define a clear opportunity profile'}</h2><p>{locale==='ar'?'حدد الأنشطة المتحكم فيها والمناطق المخدومة والأحجام المقبولة وأسباب الاستبعاد.':'Document your proven activities, served regions, acceptable contract sizes and exclusion criteria.'}</p><blockquote>{locale==='ar'?'تأتي الملاءمة من ملف واضح، لا من قائمة لا تنتهي من الكلمات المفتاحية.':'Relevance comes from a clear profile, not an endless list of keywords.'}</blockquote><h2 id="signals">2. {locale==='ar'?'ادمج إشارات متعددة':'Combine several signals'}</h2><p>{locale==='ar'?'ادمج الموضوع وصاحب المشروع والموقع والميزانية والأجل والقدرات.':'Combine scope, buyer, location, budget, deadline and capacity requirements.'}</p></div></div></article></main>; }

function LocalizedFAQ({ locale, preview=false }) { const q=preview?localizedContent[locale].faq.slice(0,4):localizedContent[locale].faq; return <section className="section faq-section"><div className="container faq-layout"><div><div className="section-label">{localizedContent[locale].common.faq}</div><h2>{locale==='ar'?'أجوبة واضحة قبل الانطلاق.':'Clear answers before you start.'}</h2><Link href={localizedHref(locale,'/contact')}>{localizedContent[locale].common.contact}<ArrowRight/></Link></div><div className="accordion">{q.map(([question,answer])=><details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></div></section>; }

function Legal({ locale, data }) { return <main id="main"><PageIntro label={localizedContent[locale].common.trust} title={data[0]} text={data[1]}/><section className="section legal-section"><div className="container"><div className="legal-alert"><ShieldCheck/><p>{locale==='ar'?'وثيقة قبل الإطلاق تحتاج إلى استكمال ومراجعة قانونية.':'Pre-launch document requiring completion and legal review.'}</p></div>{data[2].map(([title,text],i)=><section key={title}><span>0{i+1}</span><div><h2>{title}</h2><p>{text}</p></div></section>)}</div></section></main>; }

function FinalCTA({ locale }) { const h=localizedContent[locale].home; return <section className="final-cta"><div className="cta-grid"/><div className="container"><span>{h.finalLabel}</span><h2>{h.finalTitle}</h2><p>{h.finalText}</p><div><Link className="button white" href={company.appUrl}>{h.finalPrimary}<ArrowRight/></Link><Link className="button dark-ghost" href={localizedHref(locale,'/contact')}>{h.finalSecondary}</Link></div></div></section>; }

function Footer({ locale }) { const c=localizedContent[locale].common; return <footer><div className="container footer-main"><div className="footer-brand"><Logo locale={locale} light/><p>{locale==='ar'?'ذكاء تشغيلي لاكتشاف فرص الصفقات العمومية وفهمها وتدبيرها في المغرب.':'Operational intelligence to discover, understand and manage public procurement opportunities in Morocco.'}</p><span>{locale==='ar'?'أكادير · المغرب':'Agadir · Morocco'}</span></div><div><b>{c.product}</b>{productNav.slice(0,5).map(([path,key])=><Link key={path} href={localizedHref(locale,path)}>{c[key]}</Link>)}</div><div><b>{c.company}</b><Link href={localizedHref(locale,'/a-propos')}>{c.about}</Link><Link href={localizedHref(locale,'/ressources')}>{c.resources}</Link><Link href={localizedHref(locale,'/tarifs')}>{c.pricing}</Link><Link href={localizedHref(locale,'/contact')}>{c.contact}</Link></div><div><b>{c.trust}</b><Link href={localizedHref(locale,'/confidentialite')}>{c.privacy}</Link><Link href={localizedHref(locale,'/conditions')}>{c.terms}</Link><Link href={localizedHref(locale,'/cookies')}>{c.cookies}</Link><Link href={localizedHref(locale,'/ia-responsable')}>{c.responsibleAI}</Link><Link href={localizedHref(locale,'/sources')}>{c.sources}</Link></div></div><div className="container disclaimer">{c.disclaimer}</div><div className="container footer-bottom"><span>© 2026 Bido.ma</span><Link href={localizedHref(locale,'/mentions-legales')}>{c.legal}</Link></div></footer>; }

function PageRouter({ locale, pathname }) { const l=localizedContent[locale]; if(pathname==='/')return <Home locale={locale}/>; if(l.products[pathname])return <StandardPage locale={locale} data={l.products[pathname]} path={pathname}/>; if(l.solutions[pathname])return <StandardPage locale={locale} data={l.solutions[pathname]} solution/>; if(l.legal[pathname])return <Legal locale={locale} data={l.legal[pathname]}/>; if(pathname==='/tarifs')return <Pricing locale={locale}/>; if(pathname==='/a-propos')return <About locale={locale}/>; if(pathname==='/contact')return <Contact locale={locale}/>; if(pathname==='/demo')return <Contact locale={locale} demo/>; if(pathname==='/faq')return <main id="main"><PageIntro label={l.common.faq} title={locale==='ar'?'الأسئلة المهمة، بأجوبة واضحة.':'Important questions, answered clearly.'} text={locale==='ar'?'المنتج والبيانات والذكاء الاصطناعي والنشر.':'Product, data, artificial intelligence and deployment.'}/><LocalizedFAQ locale={locale}/></main>; if(pathname==='/blog')return <BlogIndex locale={locale}/>; if(pathname.startsWith('/blog/'))return <BlogArticle locale={locale} slug={pathname.split('/').pop()}/>; if(pathname==='/ressources')return <Resources locale={locale}/>; if(pathname.startsWith('/ressources/'))return <Article locale={locale}/>; return <main id="main" className="not-found"><div><span>404</span><h1>{locale==='ar'?'الصفحة غير موجودة':'Page not found'}</h1><Link className="button" href={localizedHref(locale,'/')}>{locale==='ar'?'العودة إلى الرئيسية':'Back home'}</Link></div></main>; }

export default function LocalizedApp({ locale, pathname }) { return <div className="locale-shell" lang={locale} dir={locale==='ar'?'rtl':'ltr'}><a className="skip-link" href="#main">{locale==='ar'?'الانتقال إلى المحتوى':'Skip to content'}</a><Header locale={locale} pathname={pathname}/><PageRouter locale={locale} pathname={pathname}/><Footer locale={locale}/></div>; }
