export const localizedContent = {
  en: {
    languageName: 'English',
    common: {
      demo: 'Book a demo', login: 'Sign in', menu: 'Menu', close: 'Close', language: 'Language',
      product: 'Product', solutions: 'Solutions', pricing: 'Pricing', resources: 'Resources', company: 'Company',
      platform: 'Platform overview', opportunities: 'Opportunity discovery', tenderAnalysis: 'Tender intelligence',
      documents: 'Document analysis', agents: 'AI agents', collaboration: 'Team collaboration', alerts: 'Alerts & monitoring',
      reporting: 'Reporting & exports', security: 'Security', integrations: 'Integrations', about: 'About', contact: 'Contact',
      faq: 'FAQ', readMore: 'Learn more', explore: 'Explore', capabilities: 'Capabilities', workflow: 'A complete workflow',
      detect: 'Detect', qualify: 'Qualify', analyze: 'Analyze', decide: 'Decide', requestDemo: 'Request a demo', seePricing: 'View pricing',
      disclaimer: 'Bido.ma is an independent technology platform and is not affiliated with or endorsed by any public authority. Always verify official documents, deadlines and requirements through the relevant official sources.',
      trust: 'Trust', privacy: 'Privacy policy', terms: 'Terms of service', cookies: 'Cookie policy', responsibleAI: 'Responsible AI', sources: 'Sources & attribution', legal: 'Legal notice',
    },
    home: {
      eyebrow: 'Public procurement intelligence',
      hero: 'Morocco’s first AI-powered public procurement analyzer',
      sub: 'Bido detects, qualifies and structures public procurement opportunities, turning fragmented monitoring into clear, actionable decisions.',
      primary: 'Discover Bido', secondary: 'See how it works',
      notice: 'Early access is now open to Moroccan businesses.', noticeCta: 'Join the waitlist',
      proof: 'Built in Morocco for the operational realities of Moroccan businesses.',
      trusted: 'Designed for teams that bid methodically',
      problemLabel: 'The challenge', problemTitle: 'The right opportunity exists. The challenge is seeing it in time.',
      problemLead: 'Your teams should not spend their day searching, opening and sorting files. They should decide where their expertise matters most.',
      problems: [
        ['Hours of monitoring', 'Manual searches scatter attention across low-relevance notices.'],
        ['Dense tender files', 'Critical requirements are buried across dozens of documents.'],
        ['Fragmented decisions', 'Notes, approvals and responsibilities are spread across multiple channels.'],
      ],
      platformLabel: 'The platform', platformTitle: 'One environment. From monitoring to decision.',
      platformText: 'Bido structures every stage of your workflow to create a clear, comparable and manageable pipeline.',
      steps: [
        ['Detect', 'Centralize opportunities and filter them by activity, location and priority.'],
        ['Qualify', 'Measure how well each opportunity matches your profile and capacity.'],
        ['Understand', 'Summarize tender files and surface the requirements that matter.'],
        ['Coordinate', 'Assign, discuss and document every decision with your team.'],
      ],
      discoveryLabel: 'Opportunity discovery', discoveryTitle: 'Turn monitoring into an operational advantage.',
      discoveryText: 'Create search profiles aligned with your business. Bido surfaces useful signals without overwhelming your team.',
      discoveryPoints: ['Sector, geographic and semantic filters', 'Saved searches and intelligent alerts', 'Explainable relevance scoring'],
      discoveryCta: 'Explore Bido monitoring',
      documentLabel: 'Document intelligence', documentTitle: 'From raw documents to structured understanding.',
      documentText: 'Bido extracts useful information, flags attention points and helps you build a verifiable analysis without hiding the source.',
      aiRule: 'AI assists. Your team decides.', aiRuleText: 'Every important summary remains subject to human review.', documentCta: 'Explore document analysis',
      impactLabel: 'Operational impact', impactTitle: 'Less friction. More useful decisions.',
      outcomes: [
        ['See earlier', 'Identify relevant opportunities before the deadline becomes a constraint.'],
        ['Read faster', 'Access structured summaries while keeping the connection to source documents.'],
        ['Decide together', 'Formalize your criteria and maintain a clear record of decisions.'],
        ['Respond methodically', 'Organize actions, requirements and responsibilities in one workflow.'],
      ],
      finalLabel: 'Ready to structure your monitoring?', finalTitle: 'Public procurement requires method. So does Bido.',
      finalText: 'Join businesses testing a new generation of monitoring and tender-analysis tools.', finalPrimary: 'Request early access', finalSecondary: 'Talk to the team',
    },
    products: {
      '/plateforme': ['The platform', 'One command center for your public procurement workflow', 'Centralize monitoring, analysis, qualification and preparation in an environment designed for Moroccan teams.', [['A readable pipeline', 'Move from detected opportunity to documented decision.'], ['A knowledge base', 'Keep documents, analyses, comments and decisions together.'], ['Consistent execution', 'Standardize methods without constraining your teams.']]],
      '/opportunites': ['Opportunity discovery', 'Find the opportunities that deserve your attention', 'Turn a large volume of heterogeneous notices into a focused selection aligned with your business, regions and capabilities.', [['Structured search', 'Filter by sector, buyer, location, budget and deadline.'], ['Relevance profiles', 'Define what a strong opportunity means for your company.'], ['Saved monitoring', 'Keep searches and receive useful new opportunities.']]],
      '/analyse-appels-offres': ['Tender intelligence', 'Understand faster. Decide methodically.', 'Summarize critical tender points and structure go/no-go decisions with verifiable evidence.', [['Guided reading', 'Surface scope, requirements, deadlines and attention points.'], ['Qualification framework', 'Compare each opportunity with your capacities and priorities.'], ['Decision log', 'Keep reasons, reservations and internal approvals.']]],
      '/analyse-documents': ['Document intelligence', 'Turn large tender files into actionable information', 'Ask questions, locate important clauses and build checklists grounded in source documents.', [['Contextual analysis', 'Ask questions grounded in the uploaded tender files.'], ['Structured extraction', 'Organize dates, amounts, criteria and deliverables.'], ['Traceability', 'Return to the official source before every decision.']]],
      '/agents-ia': ['Configurable agents', 'AI assistants governed by your processes', 'Configure specialized agents to monitor, analyze, compare or prepare with explicit rules, sources and limits.', [['Monitoring agent', 'Tracks defined scopes and prepares a focused selection.'], ['Analysis agent', 'Applies your evaluation framework to each file.'], ['Preparation agent', 'Structures actions and required documents without replacing experts.']]],
      '/collaboration': ['Team collaboration', 'Make shared decisions without losing context', 'Assign responsibilities, centralize observations and maintain a clear timeline for every tender.', [['Shared workspaces', 'Bring the team together around the same file.'], ['Assigned actions', 'Clarify who prepares, checks and approves.'], ['Durable context', 'Prevent information from disappearing across messages.']]],
      '/alertes': ['Monitoring', 'Stay ahead of every deadline', 'Organize useful monitoring and contextual reminders without adding more noise to the day.', [['Monitoring rules', 'Choose sectors, regions, buyers and keywords.'], ['Critical calendar', 'See the milestones that require action.'], ['Useful notifications', 'Prioritize what genuinely needs intervention.']]],
      '/reporting': ['Reporting & exports', 'Make the pipeline visible to decision-makers', 'Track coverage, pipeline quality and decisions through concise, exportable views.', [['Dashboards', 'Read volumes, statuses, sectors and deadlines.'], ['Clean exports', 'Share structured lists with stakeholders.'], ['Activity reviews', 'Run commercial reviews from the same reliable data.']]],
      '/integrations': ['Integrations', 'Bido fits into your working environment', 'Connect the channels and tools that move your information without complicating adoption.', [['Messaging', 'Receive alerts and summaries in familiar channels.'], ['Data', 'Export structured lists for internal processing.'], ['Tailored integration', 'Assess integrations for advanced environments.']]],
      '/securite': ['Security & trust', 'Trust is built through concrete controls', 'Bido follows security-by-design principles, clear access separation and human-supervised AI.', [['Access control', 'Limit information and actions by responsibility.'], ['Documented practices', 'Centralize security and retention decisions.'], ['Responsible use', 'Treat AI output as assistance, never automatic truth.']]],
    },
    solutions: {
      '/solutions/pme': ['SMEs', 'Turn a small team into a structured monitoring unit', 'Reduce search workload and focus your resources on genuinely aligned opportunities.'],
      '/solutions/entreprises': ['Enterprise', 'Unify monitoring across business units and entities', 'Give management a consolidated view without removing operational autonomy.'],
      '/solutions/bid-managers': ['Bid managers', 'Manage every bid with greater continuity', 'Bring requirements, responsibilities, risks and decisions into one living file.'],
      '/solutions/developpement-commercial': ['Business development', 'Build a qualified public-sector pipeline', 'Detect useful signals earlier and prepare clearer commercial decisions.'],
      '/solutions/consultants': ['Consultants', 'Scale analysis without diluting expertise', 'Improve consistency across deliverables while keeping professional judgment central.'],
      '/secteurs/btp': ['Construction & engineering', 'Read projects through capacity and risk', 'Structure locations, qualifications, resources, deadlines and evidence.'],
      '/secteurs/it': ['IT & digital', 'Find digital needs aligned with your offer', 'Monitor software, infrastructure, services and digital-transformation opportunities.'],
      '/secteurs/services': ['Business services', 'Bring precision to multisector monitoring', 'Filter cleaning, maintenance, training and consulting opportunities by expertise.'],
      '/secteurs/fournitures': ['Supplies & equipment', 'Target consultations with stronger fit', 'Combine purchase families, delivery locations, volumes and administrative constraints.'],
    },
    pricing: {
      label: 'Pricing', title: 'A simple structure. Capabilities that grow with you.', text: 'Final prices will be published before launch. No invented prices and no hidden commitments.',
      plans: [['Starter','Essential monitoring',['1 user','3 monitoring profiles','Email alerts','Saved lists','Essential summaries']],['Professional','Complete pipeline',['5 users','Unlimited monitoring','Document analysis','Collaboration','Reporting & exports']],['Business','Advanced teams',['15 users','Team spaces','Advanced roles','Configurable agents','Priority support']],['Enterprise','Tailored scope',['Multiple entities','SSO on assessment','Dedicated integrations','Onboarding support','Adapted contractual framework']]],
      demand: 'On request', note: 'Pricing adapted to scope', cta: 'Contact us', transparency: 'Transparency before commitment.', transparencyText: 'Functional scope, usage limits, support and data-processing conditions are documented in each offer.',
    },
    about: { label:'About', title:'Building a decision infrastructure for public procurement.', text:'Bido started from a simple observation: Moroccan businesses need to turn scattered information into a controlled process.', vision:'Our direction', visionTitle:'Useful technology, grounded in operations.', paragraphs:['Bido brings monitoring, document reading, qualification and collaboration together. It does not replace expertise; it gives expertise a faster, more traceable and consistent framework.','We build around three principles: source precision, human responsibility and ease of adoption.'], values:[['Clarity','Make opportunities and requirements easier to understand.'],['Discipline','Turn good practices into repeatable workflows.'],['Responsibility','Keep people at the center of every important decision.']] },
    contact: { contactLabel:'Contact us', demoLabel:'Early access', contactTitle:'A precise question deserves a precise answer.', demoTitle:'Let’s see how Bido can support your team.', contactText:'Product, partnership, security or support: give us the context that matters.', demoText:'Tell us about your context. We will contact you to prepare a demonstration aligned with your workflow.', name:'Full name', email:'Work email', business:'Company', role:'Role', team:'Team size', sector:'Sector', need:'Your needs', message:'How can we help?', demoMessage:'Briefly describe your current process…', consent:'I agree that Bido may process this information to respond to my request.', send:'Send request', request:'Request access', localNotice:'No data is transmitted in this demonstration version.', success:'Request saved locally', successText:'This demonstration does not send data. Connect the form to your endpoint before production.' },
    resources: { label:'Resource center', title:'Methods to detect, decide and respond better.', text:'Guides, checklists and analysis for business-development and bid teams.', cards:[['Guide','Structure public procurement monitoring in six steps','A practical method for moving from daily searching to a manageable system.'],['Analysis','Build a useful go/no-go framework','Criteria for aligning capacity, risk and commercial priority.'],['Method','Read a tender file without losing the thread','A sequence focused on requirements, evidence and responsibilities.'],['Responsible AI','Use AI without losing control','Essential safeguards for document analysis.'],['Checklist','Prepare a bid kick-off meeting','Information to gather before opening a new file.'],['Glossary','Key public procurement terms','A simple reference for consistent team language.']] },
    faq: [['Is Bido an official public portal?','No. Bido is an independent technology platform and is not affiliated with or endorsed by any public authority.'],['Can AI decide for my team?','No. AI accelerates reading and structuring; your experts retain validation and decision authority.'],['What opportunities are covered?','Coverage is progressively focused on notices and consultations useful to Moroccan businesses.'],['Can I configure sectors and regions?','Yes. Monitoring profiles combine activities, locations, keywords, buyers and internal criteria.'],['How are documents handled?','Retention, hosting and security commitments will be published contractually before launch.'],['Is there a multi-entity offer?','Yes. Enterprise is designed for organizations with multiple teams, entities or access rules.']],
    legal: {
      '/confidentialite':['Privacy policy','This pre-launch privacy framework must be completed and legally validated before production.',[['Data processed','Account, usage and contact data is limited to what the service requires.'],['Purpose and legal basis','Every process must have a clear purpose, legal basis and retention period.'],['Your rights','Access, correction, objection and deletion procedures will be documented.'],['Processors','Providers and processing locations will be listed before launch.']]],
      '/conditions':['Terms of service','This product framework requires professional legal review before commercial launch.',[['Service scope','Bido provides monitoring, organization and analysis-assistance tools.'],['Responsibility','Users remain responsible for checking sources, dates and submission conditions.'],['Availability','Service and support commitments will be defined contractually.'],['Intellectual property','Content, data and output rights will be specified in the agreement.']]],
      '/cookies':['Cookie policy','Bido provides granular consent. Non-essential cookies stay disabled before your choice.',[['Necessary','Essential operation and consent preferences.'],['Analytics','Optional category for aggregate site usage.'],['Preferences','Stores additional settings when authorized.'],['Management','Change your choice from the footer at any time.']]],
      '/mentions-legales':['Legal notice','Final corporate information must be supplied before commercial publication.',[['Publisher','Legal name, form, capital and identifiers to be completed.'],['Registered office','Official address to be completed.'],['Publication director','Identity to be completed.'],['Hosting','Provider and details to be completed.']]],
      '/ia-responsable':['Responsible AI statement','Bido AI is operational assistance governed by professional judgment.',[['Human oversight','Important output must be reviewed before decisions or submissions.'],['Transparency','The interface distinguishes sources, extractions and generated summaries.'],['Known limits','Answers may be incomplete or wrong; official documents remain authoritative.'],['Improvement','Feedback and incidents support ongoing control and improvement.']]],
      '/sources':['Sources & attribution','Bido organizes publicly available information without replacing official platforms.',[['Independence','Bido is not affiliated with any public authority.'],['Verification','Users must verify notices, documents and deadlines through official sources.'],['Updates','Aggregated information may change; timestamp and source should guide verification.'],['Reporting','A channel will allow inaccurate or outdated data to be reported.']]],
    },
  },
  ar: {
    languageName: 'العربية',
    common: {
      demo: 'طلب عرض توضيحي', login: 'تسجيل الدخول', menu: 'القائمة', close: 'إغلاق', language: 'اللغة',
      product: 'المنتج', solutions: 'الحلول', pricing: 'الأسعار', resources: 'الموارد', company: 'الشركة',
      platform: 'نظرة عامة', opportunities: 'اكتشاف الفرص', tenderAnalysis: 'تحليل طلبات العروض', documents: 'تحليل الوثائق',
      agents: 'وكلاء الذكاء الاصطناعي', collaboration: 'تعاون الفريق', alerts: 'التنبيهات والمراقبة', reporting: 'التقارير والتصدير',
      security: 'الأمان', integrations: 'التكاملات', about: 'من نحن', contact: 'اتصل بنا', faq: 'الأسئلة الشائعة',
      readMore: 'اعرف المزيد', explore: 'استكشف', capabilities: 'الإمكانات', workflow: 'مسار عمل متكامل',
      detect: 'اكتشاف', qualify: 'تأهيل', analyze: 'تحليل', decide: 'قرار', requestDemo: 'طلب عرض توضيحي', seePricing: 'عرض الأسعار',
      disclaimer: 'Bido.ma منصة تكنولوجية مستقلة، ولا تتبع ولا تحظى بمصادقة أي جهة عمومية. يجب دائماً التحقق من الوثائق والآجال والشروط عبر المصادر الرسمية المعنية.',
      trust: 'الثقة', privacy: 'سياسة الخصوصية', terms: 'شروط الاستخدام', cookies: 'سياسة ملفات الارتباط', responsibleAI: 'ذكاء اصطناعي مسؤول', sources: 'المصادر والإسناد', legal: 'البيانات القانونية',
    },
    home: {
      eyebrow: 'ذكاء الصفقات العمومية', hero: 'أول محلّل بالذكاء الاصطناعي للصفقات العمومية في المغرب',
      sub: 'تكتشف Bido فرص الصفقات العمومية وتؤهلها وتنظمها، لتحول عملية الرصد المتفرقة إلى قرارات واضحة وقابلة للتنفيذ.',
      primary: 'اكتشف Bido', secondary: 'كيف تعمل المنصة', notice: 'فُتح باب الولوج المبكر أمام المقاولات المغربية.', noticeCta: 'انضم إلى قائمة الانتظار',
      proof: 'منصة مطورة في المغرب لتلائم الواقع العملي للمقاولات المغربية.', trusted: 'مصممة للفرق التي تستجيب بمنهجية',
      problemLabel: 'التحدي', problemTitle: 'الفرصة المناسبة موجودة. التحدي هو اكتشافها في الوقت المناسب.',
      problemLead: 'لا ينبغي لفرقكم أن تقضي يومها في البحث وفتح الملفات وفرزها، بل في تحديد الفرص التي تستحق خبرتها.',
      problems: [['ساعات من الرصد','يشتت البحث اليدوي الانتباه بين إعلانات ضعيفة الصلة.'],['ملفات كثيفة','تتوزع الشروط الحاسمة بين عشرات الوثائق.'],['قرارات متفرقة','تتوزع الملاحظات والموافقات والمسؤوليات بين قنوات متعددة.']],
      platformLabel: 'المنصة', platformTitle: 'بيئة واحدة، من الرصد إلى القرار.', platformText: 'تنظم Bido كل مرحلة من المسار لإنشاء محفظة واضحة وقابلة للمقارنة والتدبير.',
      steps: [['اكتشف','اجمع الفرص وصفّها حسب النشاط والموقع والأولوية.'],['أهّل','قيّم مدى ملاءمة كل فرصة لملفكم وقدراتكم.'],['افهم','لخّص الملفات وأبرز الشروط الأساسية.'],['نسّق','وزع المهام ووثق كل قرار داخل الفريق.']],
      discoveryLabel: 'اكتشاف الفرص', discoveryTitle: 'حوّل الرصد إلى ميزة تشغيلية.', discoveryText: 'أنشئ ملفات بحث متوافقة مع نشاطكم، ودع Bido تبرز الإشارات المفيدة دون إغراق الفريق.',
      discoveryPoints: ['مرشحات قطاعية وجغرافية ودلالية','عمليات بحث محفوظة وتنبيهات ذكية','درجة ملاءمة قابلة للتفسير'], discoveryCta: 'استكشف رصد Bido',
      documentLabel: 'ذكاء الوثائق', documentTitle: 'من الوثيقة الخام إلى فهم منظم.', documentText: 'تستخرج Bido المعلومات المهمة، وتبرز نقاط الانتباه، وتساعدكم على إعداد تحليل قابل للتحقق مع الحفاظ على المصدر.',
      aiRule: 'الذكاء الاصطناعي يساعد، وفريقكم يقرر.', aiRuleText: 'تظل كل خلاصة مهمة خاضعة للمراجعة البشرية.', documentCta: 'استكشف تحليل الوثائق',
      impactLabel: 'الأثر التشغيلي', impactTitle: 'تعقيد أقل، وقرارات أكثر فائدة.',
      outcomes: [['اكتشاف مبكر','حدد الفرص المناسبة قبل أن يصبح الأجل عائقاً.'],['قراءة أسرع','اطلع على خلاصة منظمة مع الرجوع إلى الوثائق الأصلية.'],['قرار جماعي','وحّد المعايير واحتفظ بسجل واضح للقرارات.'],['استجابة منهجية','نظم الإجراءات والشروط والمسؤوليات في مسار واحد.']],
      finalLabel: 'هل أنتم مستعدون لتنظيم عملية الرصد؟', finalTitle: 'الصفقات العمومية تتطلب منهجية، وكذلك Bido.', finalText: 'انضموا إلى المقاولات التي تختبر جيلاً جديداً من أدوات الرصد والتحليل.', finalPrimary: 'طلب الولوج المبكر', finalSecondary: 'تحدث مع الفريق',
    },
    products: {
      '/plateforme':['المنصة','مركز قيادة موحد لمسار الصفقات العمومية','اجمع الرصد والتحليل والتأهيل والإعداد في بيئة مصممة للفرق المغربية.',[['محفظة واضحة','انتقل من اكتشاف الفرصة إلى قرار موثق.'],['قاعدة معرفة','احتفظ بالوثائق والتحليلات والتعليقات والقرارات.'],['تنفيذ منسجم','وحّد المنهجية دون تقييد الفرق.']]],
      '/opportunites':['اكتشاف الفرص','اكتشف الفرص التي تستحق اهتمامكم','حوّل عدداً كبيراً من الإعلانات المتنوعة إلى قائمة عملية متوافقة مع نشاطكم ومناطقكم وقدراتكم.',[['بحث منظم','صفِّ حسب القطاع وصاحب المشروع والموقع والميزانية والأجل.'],['ملفات الملاءمة','حدد خصائص الفرصة المناسبة لمقاولتكم.'],['عمليات رصد محفوظة','احتفظ بالبحث وتوصل بالفرص الجديدة المفيدة.']]],
      '/analyse-appels-offres':['ذكاء طلبات العروض','افهم أسرع واتخذ القرار بمنهجية','لخّص النقاط الحاسمة ونظم قرار المشاركة أو عدمها بأدلة قابلة للتحقق.',[['قراءة موجهة','أبرز موضوع الصفقة والشروط والآجال ونقاط الانتباه.'],['شبكة التأهيل','قارن الفرصة بقدراتكم وأولوياتكم.'],['سجل القرار','احتفظ بالأسباب والتحفظات والموافقات الداخلية.']]],
      '/analyse-documents':['ذكاء الوثائق','حوّل الملفات الكبيرة إلى معلومات قابلة للتنفيذ','اطرح الأسئلة وحدد البنود المهمة وأنشئ قوائم تحقق مرتبطة بالوثائق الأصلية.',[['تحليل سياقي','اطرح أسئلة مبنية على محتوى الملفات.'],['استخراج منظم','نظم التواريخ والمبالغ والمعايير والمخرجات.'],['قابلية التتبع','ارجع إلى المصدر الرسمي قبل اتخاذ القرار.']]],
      '/agents-ia':['وكلاء قابلون للضبط','مساعدون بالذكاء الاصطناعي تحكمهم مساراتكم','اضبط وكلاء متخصصين للرصد والتحليل والمقارنة والإعداد بقواعد ومصادر وحدود واضحة.',[['وكيل الرصد','يتابع النطاق المحدد ويعد قائمة مركزة.'],['وكيل التحليل','يطبق شبكة التقييم على كل ملف.'],['وكيل الإعداد','ينظم الإجراءات والوثائق دون تعويض الخبراء.']]],
      '/collaboration':['تعاون الفريق','اتخذوا القرار معاً دون فقدان السياق','وزع المسؤوليات واجمع الملاحظات واحتفظ بتسلسل واضح لكل ملف.',[['مساحات مشتركة','اجمع الفريق حول الملف نفسه.'],['إجراءات مسندة','حدد من يُعد ومن يراجع ومن يصادق.'],['سياق محفوظ','تجنب ضياع المعلومات بين الرسائل.']]],
      '/alertes':['المراقبة','ابقَ متقدماً على الآجال','نظم الرصد والتذكيرات السياقية دون إضافة ضوضاء إلى يوم العمل.',[['قواعد الرصد','اختر القطاعات والمناطق وأصحاب المشاريع والكلمات المفتاحية.'],['جدول حاسم','شاهد المراحل التي تتطلب إجراءً.'],['إشعارات مفيدة','أعط الأولوية لما يحتاج تدخلاً فعلياً.']]],
      '/reporting':['التقارير والتصدير','اجعل المحفظة واضحة لصناع القرار','تابع التغطية وجودة المحفظة والقرارات عبر عروض موجزة قابلة للتصدير.',[['لوحات القيادة','اقرأ الأحجام والحالات والقطاعات والآجال.'],['تصدير منظم','شارك قوائم واضحة مع الأطراف المعنية.'],['مراجعة النشاط','أدر الاجتماعات التجارية انطلاقاً من البيانات نفسها.']]],
      '/integrations':['التكاملات','تندمج Bido في بيئة عملكم','اربط القنوات والأدوات التي تنقل معلوماتكم دون تعقيد الانطلاقة.',[['المراسلة','استقبل التنبيهات والخلاصات في القنوات المعتادة.'],['البيانات','صدّر القوائم المنظمة لمعالجتها داخلياً.'],['تكامل مخصص','ندرس التكاملات المناسبة للبيئات المتقدمة.']]],
      '/securite':['الأمان والثقة','الثقة تُبنى عبر ضوابط ملموسة','تعتمد Bido الأمان منذ التصميم وفصل الصلاحيات والإشراف البشري على الذكاء الاصطناعي.',[['التحكم في الولوج','حدد المعلومات والإجراءات حسب المسؤولية.'],['ممارسات موثقة','وثق قرارات الأمان والاحتفاظ.'],['استخدام مسؤول','اعتبر مخرجات الذكاء الاصطناعي مساعدة وليست حقيقة تلقائية.']]],
    },
    solutions: {
      '/solutions/pme':['المقاولات الصغرى والمتوسطة','حوّل فريقاً صغيراً إلى وحدة رصد منظمة','خفف عبء البحث وركز الموارد على الفرص المتوافقة فعلاً.'],
      '/solutions/entreprises':['المقاولات الكبرى','وحّد الرصد بين الأنشطة والكيانات','امنح الإدارة رؤية موحدة مع الحفاظ على الاستقلالية التشغيلية.'],
      '/solutions/bid-managers':['مديرو العروض','دبّر كل عرض باستمرارية أكبر','اجمع الشروط والمسؤوليات والمخاطر والقرارات في ملف حي.'],
      '/solutions/developpement-commercial':['تطوير الأعمال','أنشئ محفظة مؤهلة للقطاع العام','اكتشف الإشارات المفيدة مبكراً واتخذ قرارات تجارية أوضح.'],
      '/solutions/consultants':['المستشارون','وسع التحليل دون إضعاف الخبرة','حسن اتساق المخرجات مع إبقاء الحكم المهني في المركز.'],
      '/secteurs/btp':['البناء والهندسة','اقرأ المشاريع بمنطق القدرة والمخاطر','نظم المواقع والتأهيلات والوسائل والآجال والوثائق.'],
      '/secteurs/it':['التكنولوجيا والرقمنة','اكتشف الحاجات الرقمية الملائمة لعرضكم','تابع فرص البرمجيات والبنية التحتية والخدمات والتحول الرقمي.'],
      '/secteurs/services':['خدمات المقاولات','أضف الدقة إلى الرصد متعدد القطاعات','صفِّ فرص النظافة والصيانة والتكوين والاستشارة حسب خبراتكم.'],
      '/secteurs/fournitures':['التوريدات والتجهيزات','استهدف الاستشارات الأكثر ملاءمة','ادمج فئات الشراء ومواقع التسليم والكميات والشروط الإدارية.'],
    },
    pricing: { label:'الأسعار', title:'هيكلة بسيطة وإمكانات تنمو معكم.', text:'ستنشر الأسعار النهائية قبل الإطلاق، دون أسعار وهمية أو التزامات مخفية.', plans:[['البداية','الرصد الأساسي',['مستخدم واحد','3 ملفات رصد','تنبيهات بالبريد','قوائم محفوظة','خلاصات أساسية']],['احترافي','محفظة متكاملة',['5 مستخدمين','رصد غير محدود','تحليل الوثائق','التعاون','التقارير والتصدير']],['الأعمال','فرق متقدمة',['15 مستخدماً','مساحات للفرق','صلاحيات متقدمة','وكلاء قابلون للضبط','دعم بأولوية']],['المؤسسات','نطاق مخصص',['كيانات متعددة','دخول موحد حسب الدراسة','تكاملات خاصة','مواكبة الانطلاقة','إطار تعاقدي مناسب']]], demand:'حسب الطلب', note:'السعر ملائم للنطاق', cta:'اتصل بنا', transparency:'شفافية قبل الالتزام.', transparencyText:'يتم توثيق النطاق الوظيفي وحدود الاستخدام والدعم وشروط معالجة البيانات في كل عرض.' },
    about: { label:'من نحن', title:'نبني بنية تحتية للقرار في الصفقات العمومية.', text:'انطلقت Bido من ملاحظة بسيطة: تحتاج المقاولات المغربية إلى تحويل المعلومات المتفرقة إلى مسار مضبوط.', vision:'توجهنا', visionTitle:'تكنولوجيا مفيدة مرتبطة بالعمليات.', paragraphs:['تجمع Bido الرصد وقراءة الوثائق والتأهيل والتعاون. لا تعوض الخبرة، بل تمنحها إطاراً أسرع وأكثر اتساقاً وقابلية للتتبع.','نبني المنتج حول ثلاثة مبادئ: دقة المصادر، والمسؤولية البشرية، وسهولة الاعتماد.'], values:[['الوضوح','تسهيل فهم الفرص وشروطها.'],['الانضباط','تحويل الممارسات الجيدة إلى مسار قابل للتكرار.'],['المسؤولية','إبقاء الإنسان في مركز كل قرار مهم.']] },
    contact: { contactLabel:'اتصل بنا', demoLabel:'الولوج المبكر', contactTitle:'السؤال الدقيق يستحق جواباً دقيقاً.', demoTitle:'لنرَ كيف يمكن لـ Bido مساعدة فريقكم.', contactText:'المنتج أو الشراكة أو الأمان أو المواكبة: قدموا لنا السياق المفيد.', demoText:'عرّفونا بسياقكم وسنتواصل معكم لإعداد عرض ملائم لمساركم.', name:'الاسم الكامل', email:'البريد المهني', business:'المقاولة', role:'الوظيفة', team:'حجم الفريق', sector:'القطاع', need:'حاجتكم', message:'كيف يمكننا مساعدتكم؟', demoMessage:'صفوا بإيجاز مساركم الحالي…', consent:'أوافق على معالجة Bido لهذه المعلومات للرد على طلبي.', send:'إرسال الطلب', request:'طلب الولوج', localNotice:'لا تُرسل أي بيانات في هذه النسخة التجريبية.', success:'حُفظ الطلب محلياً', successText:'هذه النسخة لا ترسل البيانات. اربط النموذج بنقطة الاستقبال قبل الإنتاج.' },
    resources: { label:'مركز الموارد', title:'منهجيات لاكتشاف أفضل وقرار أفضل واستجابة أفضل.', text:'أدلة وقوائم تحقق وتحليلات لفرق تطوير الأعمال وإعداد العروض.', cards:[['دليل','تنظيم رصد الصفقات العمومية في ست مراحل','منهج عملي للانتقال من البحث اليومي إلى نظام قابل للتدبير.'],['تحليل','بناء شبكة عملية للمشاركة أو عدمها','معايير لمواءمة القدرة والمخاطر والأولوية التجارية.'],['منهج','قراءة الملف دون فقدان الخيط','تسلسل يركز على الشروط والأدلة والمسؤوليات.'],['ذكاء مسؤول','استخدام الذكاء الاصطناعي مع الحفاظ على التحكم','ضوابط أساسية لتحليل الوثائق.'],['قائمة تحقق','إعداد اجتماع انطلاق العرض','المعلومات الواجب جمعها قبل فتح الملف.'],['معجم','مصطلحات الصفقات العمومية','مرجع بسيط لتوحيد لغة الفريق.']] },
    faq: [['هل Bido بوابة عمومية رسمية؟','لا. Bido منصة تكنولوجية مستقلة ولا تتبع أي جهة عمومية.'],['هل يقرر الذكاء الاصطناعي مكان الفريق؟','لا. يسرع القراءة والتنظيم، بينما يحتفظ الخبراء بالمراجعة والقرار.'],['ما الفرص التي تغطيها المنصة؟','تركز التغطية تدريجياً على الإعلانات والاستشارات المفيدة للمقاولات المغربية.'],['هل يمكن ضبط القطاعات والمناطق؟','نعم. تجمع ملفات الرصد بين الأنشطة والمناطق والكلمات وأصحاب المشاريع والمعايير الداخلية.'],['كيف تُعالج الوثائق؟','ستنشر التزامات الاحتفاظ والاستضافة والأمان تعاقدياً قبل الإطلاق.'],['هل يوجد عرض لعدة كيانات؟','نعم. عرض المؤسسات مخصص للمنظمات متعددة الفرق أو الكيانات أو قواعد الولوج.']],
    legal: {
      '/confidentialite':['سياسة الخصوصية','يجب استكمال هذا الإطار الأولي للخصوصية والمصادقة عليه قانونياً قبل الإطلاق.',[['البيانات المعالجة','تقتصر بيانات الحساب والاستعمال والتواصل على ما تتطلبه الخدمة.'],['الغايات والأساس القانوني','يرتبط كل علاج بغاية واضحة وأساس مناسب ومدة احتفاظ محددة.'],['حقوقكم','سيتم توضيح إجراءات الولوج والتصحيح والاعتراض والحذف.'],['المتعهدون','ستنشر لائحة مقدمي الخدمات ومواقع المعالجة قبل الإطلاق.']]],
      '/conditions':['شروط الاستخدام','يحتاج هذا الإطار الأولي إلى مراجعة قانونية مهنية قبل الإطلاق التجاري.',[['نطاق الخدمة','توفر Bido أدوات للرصد والتنظيم والمساعدة على التحليل.'],['المسؤولية','يبقى المستخدم مسؤولاً عن التحقق من المصادر والآجال وشروط الإيداع.'],['التوفر','تحدد التزامات الخدمة والدعم تعاقدياً.'],['الملكية الفكرية','توضح حقوق المحتوى والبيانات والمخرجات في الاتفاق.']]],
      '/cookies':['سياسة ملفات الارتباط','توفر Bido موافقة مفصلة، وتظل الملفات غير الضرورية معطلة قبل اختياركم.',[['الضرورية','للتشغيل الأساسي وحفظ الموافقة.'],['قياس الجمهور','فئة اختيارية لفهم الاستعمال الإجمالي.'],['التفضيلات','تحفظ الإعدادات الإضافية بعد الموافقة.'],['التدبير','يمكن تغيير الاختيار من أسفل الصفحة.']]],
      '/mentions-legales':['البيانات القانونية','يجب إضافة المعلومات القانونية النهائية قبل النشر التجاري.',[['الناشر','الاسم القانوني والشكل والرأسمال والمعرفات.'],['المقر','العنوان الرسمي.'],['مدير النشر','الهوية الواجب استكمالها.'],['الاستضافة','مقدم الخدمة وبياناته.']]],
      '/ia-responsable':['بيان الذكاء الاصطناعي المسؤول','ذكاء Bido مساعدة تشغيلية تخضع للحكم المهني.',[['الإشراف البشري','تراجع المخرجات المهمة قبل القرار أو الإيداع.'],['الشفافية','تميز الواجهة بين المصادر والاستخراج والخلاصات المولدة.'],['الحدود','قد تكون الإجابات ناقصة أو خاطئة، وتبقى الوثيقة الرسمية المرجع.'],['التحسين','تدعم الملاحظات والحوادث عملية المراقبة والتحسين.']]],
      '/sources':['المصادر والإسناد','تنظم Bido المعلومات المتاحة للعموم دون تعويض المنصات الرسمية.',[['الاستقلالية','لا تتبع Bido أي جهة عمومية.'],['التحقق','يجب التحقق من الإعلانات والوثائق والآجال عبر المصادر الرسمية.'],['التحيين','قد تتغير المعلومات المجمعة، لذا يجب مراعاة التاريخ والمصدر.'],['التبليغ','ستتوفر قناة للتبليغ عن البيانات غير الدقيقة أو القديمة.']]],
    },
  },
};

export const locales = ['fr', 'en', 'ar'];

export function localizedHref(locale, path = '/') {
  if (locale === 'fr') return path;
  return path === '/' ? `/${locale}` : `/${locale}${path}`;
}
